//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_BaoCaoHoatDongXe
    {
        public long Id { get; set; }
        public Nullable<long> IdXe { get; set; }
        public string BienSoDK { get; set; }
        public string BienSoDi { get; set; }
        public Nullable<int> IdBenDi { get; set; }
        public string TenBenDi { get; set; }
        public Nullable<int> IdBenDen { get; set; }
        public string TenBenDen { get; set; }
        public Nullable<long> IdLuongTuyen { get; set; }
        public string MaTuyen { get; set; }
        public string TenTuyen { get; set; }
        public Nullable<int> IdDonVi { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<int> SucChua { get; set; }
        public Nullable<System.DateTime> GioXuatBenKH { get; set; }
        public Nullable<System.DateTime> GioXuatBenThucTT { get; set; }
        public Nullable<int> SoKhach { get; set; }
        public string LyDo { get; set; }
    }
}
