//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_TongHop_Ben
    {
        public long Id { get; set; }
        public int BX_IdBenXe { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> SoChuyenKeHoach { get; set; }
        public Nullable<int> SoChuyenThucChay { get; set; }
        public Nullable<int> SoChuyenChenhLech { get; set; }
        public Nullable<double> TyLeThucHien { get; set; }
    }
}
