//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_TaiKhoan()
        {
            this.HT_NhatKy = new HashSet<HT_NhatKy>();
            this.Transfer_UngDungTruyenTaiDuLieu = new HashSet<Transfer_UngDungTruyenTaiDuLieu>();
        }
    
        public long IDTaiKhoan { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public Nullable<long> IDBen { get; set; }
        public Nullable<long> IDDonViVanTai { get; set; }
        public Nullable<long> IDSo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_NhatKy> HT_NhatKy { get; set; }
        public virtual HT_ThongTinTaiKhoan HT_ThongTinTaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_UngDungTruyenTaiDuLieu> Transfer_UngDungTruyenTaiDuLieu { get; set; }
    }
}
