//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLVanTai_2017 : DbContext
    {
        public QLVanTai_2017()
            : base("name=QLVanTai_2017")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC_BaoCaoHoatDongXe> BC_BaoCaoHoatDongXe { get; set; }
        public virtual DbSet<BC_CapDonViVanTai> BC_CapDonViVanTai { get; set; }
        public virtual DbSet<BC_HoatDongCapSo> BC_HoatDongCapSo { get; set; }
        public virtual DbSet<BC_HoatDongCapTuyen> BC_HoatDongCapTuyen { get; set; }
        public virtual DbSet<BC_TongHop_Ben> BC_TongHop_Ben { get; set; }
        public virtual DbSet<HT_NhatKy> HT_NhatKy { get; set; }
        public virtual DbSet<HT_PhanQuyen> HT_PhanQuyen { get; set; }
        public virtual DbSet<HT_Quyen> HT_Quyen { get; set; }
        public virtual DbSet<HT_TaiKhoan> HT_TaiKhoan { get; set; }
        public virtual DbSet<HT_ThongTinTaiKhoan> HT_ThongTinTaiKhoan { get; set; }
        public virtual DbSet<NhatTrinhXe> NhatTrinhXes { get; set; }
        public virtual DbSet<QLVT_BieuDoXeChay> QLVT_BieuDoXeChay { get; set; }
        public virtual DbSet<QLVT_CapTuyenChoTinh_So> QLVT_CapTuyenChoTinh_So { get; set; }
        public virtual DbSet<QLVT_CongTyVanTai> QLVT_CongTyVanTai { get; set; }
        public virtual DbSet<QLVT_CongTyVanTai_TrangThai> QLVT_CongTyVanTai_TrangThai { get; set; }
        public virtual DbSet<QLVT_DanhSachCapTuyenChoDN> QLVT_DanhSachCapTuyenChoDN { get; set; }
        public virtual DbSet<QLVT_LuongTuyen> QLVT_LuongTuyen { get; set; }
        public virtual DbSet<QLVT_LuongTuyen_DiemDauCuoi> QLVT_LuongTuyen_DiemDauCuoi { get; set; }
        public virtual DbSet<QLVT_LuongTuyen_DiemDauCuoi_TrangThai> QLVT_LuongTuyen_DiemDauCuoi_TrangThai { get; set; }
        public virtual DbSet<QLVT_LuongTuyen_PhanLoai> QLVT_LuongTuyen_PhanLoai { get; set; }
        public virtual DbSet<QLVT_LuongTuyen_TrangThai> QLVT_LuongTuyen_TrangThai { get; set; }
        public virtual DbSet<QLVT_ThongTinBenXe> QLVT_ThongTinBenXe { get; set; }
        public virtual DbSet<QLVT_ThongTinTinh_So_Ben_TrangThai> QLVT_ThongTinTinh_So_Ben_TrangThai { get; set; }
        public virtual DbSet<QLVT_ThongTinTinh_SoGiaoThong> QLVT_ThongTinTinh_SoGiaoThong { get; set; }
        public virtual DbSet<QLVT_ThongTinXe> QLVT_ThongTinXe { get; set; }
        public virtual DbSet<QLVT_ThongTinXe_beta> QLVT_ThongTinXe_beta { get; set; }
        public virtual DbSet<QLVT_ThongTinXe_GSHT> QLVT_ThongTinXe_GSHT { get; set; }
        public virtual DbSet<QLVT_ThongTinXe_LichSuThayDoiHopDong> QLVT_ThongTinXe_LichSuThayDoiHopDong { get; set; }
        public virtual DbSet<QLVT_ThongTinXe_TrangThaiXe> QLVT_ThongTinXe_TrangThaiXe { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_NgayBaoCao> tbl_NgayBaoCao { get; set; }
        public virtual DbSet<Transfer_NhatKyTruyenTaiDuLieu> Transfer_NhatKyTruyenTaiDuLieu { get; set; }
        public virtual DbSet<Transfer_UngDungTruyenTaiDuLieu> Transfer_UngDungTruyenTaiDuLieu { get; set; }
        public virtual DbSet<view_LuongTuyen> view_LuongTuyen { get; set; }
        public virtual DbSet<view_ThongTinXe> view_ThongTinXe { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<GetThongTinDonVi_IdTuyen_Result> GetThongTinDonVi_IdTuyen(Nullable<long> iD_Tuyen)
        {
            var iD_TuyenParameter = iD_Tuyen.HasValue ?
                new ObjectParameter("ID_Tuyen", iD_Tuyen) :
                new ObjectParameter("ID_Tuyen", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinDonVi_IdTuyen_Result>("GetThongTinDonVi_IdTuyen", iD_TuyenParameter);
        }
    
        public virtual ObjectResult<GetThongTinTuyen_IdBen_Result> GetThongTinTuyen_IdBen(Nullable<int> idBen)
        {
            var idBenParameter = idBen.HasValue ?
                new ObjectParameter("IdBen", idBen) :
                new ObjectParameter("IdBen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinTuyen_IdBen_Result>("GetThongTinTuyen_IdBen", idBenParameter);
        }
    
        public virtual ObjectResult<GetThongTinTuyen_IdSo_Result> GetThongTinTuyen_IdSo(Nullable<int> idSo)
        {
            var idSoParameter = idSo.HasValue ?
                new ObjectParameter("IdSo", idSo) :
                new ObjectParameter("IdSo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinTuyen_IdSo_Result>("GetThongTinTuyen_IdSo", idSoParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoHoatDongThuongXuyen_Result> sp_BaoCaoHoatDongThuongXuyen(string ngay, Nullable<int> iD_BenXe)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var iD_BenXeParameter = iD_BenXe.HasValue ?
                new ObjectParameter("ID_BenXe", iD_BenXe) :
                new ObjectParameter("ID_BenXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoHoatDongThuongXuyen_Result>("sp_BaoCaoHoatDongThuongXuyen", ngayParameter, iD_BenXeParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoHoatDongThuongXuyen_Ben_Result> sp_BaoCaoHoatDongThuongXuyen_Ben(string ngay, Nullable<int> iD_BenXe)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var iD_BenXeParameter = iD_BenXe.HasValue ?
                new ObjectParameter("ID_BenXe", iD_BenXe) :
                new ObjectParameter("ID_BenXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoHoatDongThuongXuyen_Ben_Result>("sp_BaoCaoHoatDongThuongXuyen_Ben", ngayParameter, iD_BenXeParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoHoatDongThuongXuyen_DanhSachDonVi_Result> sp_BaoCaoHoatDongThuongXuyen_DanhSachDonVi(string ngay, Nullable<int> iD_BenXe, Nullable<long> idTuyen)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var iD_BenXeParameter = iD_BenXe.HasValue ?
                new ObjectParameter("ID_BenXe", iD_BenXe) :
                new ObjectParameter("ID_BenXe", typeof(int));
    
            var idTuyenParameter = idTuyen.HasValue ?
                new ObjectParameter("idTuyen", idTuyen) :
                new ObjectParameter("idTuyen", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoHoatDongThuongXuyen_DanhSachDonVi_Result>("sp_BaoCaoHoatDongThuongXuyen_DanhSachDonVi", ngayParameter, iD_BenXeParameter, idTuyenParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoHoatDongThuongXuyen_DanhSachXe_Result> sp_BaoCaoHoatDongThuongXuyen_DanhSachXe(string ngay, Nullable<int> iD_BenXe, Nullable<long> id_Tuyen)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var iD_BenXeParameter = iD_BenXe.HasValue ?
                new ObjectParameter("ID_BenXe", iD_BenXe) :
                new ObjectParameter("ID_BenXe", typeof(int));
    
            var id_TuyenParameter = id_Tuyen.HasValue ?
                new ObjectParameter("Id_Tuyen", id_Tuyen) :
                new ObjectParameter("Id_Tuyen", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoHoatDongThuongXuyen_DanhSachXe_Result>("sp_BaoCaoHoatDongThuongXuyen_DanhSachXe", ngayParameter, iD_BenXeParameter, id_TuyenParameter);
        }
    
        public virtual ObjectResult<sp_BaocaoTongHop_BenXe_Result> sp_BaocaoTongHop_BenXe(Nullable<int> nam, Nullable<int> thang, Nullable<int> id_Ben)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var id_BenParameter = id_Ben.HasValue ?
                new ObjectParameter("id_Ben", id_Ben) :
                new ObjectParameter("id_Ben", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaocaoTongHop_BenXe_Result>("sp_BaocaoTongHop_BenXe", namParameter, thangParameter, id_BenParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoTongHop_So_Result> sp_BaoCaoTongHop_So(Nullable<int> nam, Nullable<int> thang, Nullable<int> id_So)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var id_SoParameter = id_So.HasValue ?
                new ObjectParameter("id_So", id_So) :
                new ObjectParameter("id_So", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoTongHop_So_Result>("sp_BaoCaoTongHop_So", namParameter, thangParameter, id_SoParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoTongHop_ToanQuoc_Result> sp_BaoCaoTongHop_ToanQuoc(Nullable<int> nam, Nullable<int> thang)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoTongHop_ToanQuoc_Result>("sp_BaoCaoTongHop_ToanQuoc", namParameter, thangParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoTongHop_DonViVanTai_Result> sp_HD_BaoCaoTongHop_DonViVanTai(string tuNgay, string denNgay, Nullable<int> id_Ben, Nullable<long> id_Tuyen, Nullable<int> id_DonVi)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_BenParameter = id_Ben.HasValue ?
                new ObjectParameter("Id_Ben", id_Ben) :
                new ObjectParameter("Id_Ben", typeof(int));
    
            var id_TuyenParameter = id_Tuyen.HasValue ?
                new ObjectParameter("Id_Tuyen", id_Tuyen) :
                new ObjectParameter("Id_Tuyen", typeof(long));
    
            var id_DonViParameter = id_DonVi.HasValue ?
                new ObjectParameter("Id_DonVi", id_DonVi) :
                new ObjectParameter("Id_DonVi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoTongHop_DonViVanTai_Result>("sp_HD_BaoCaoTongHop_DonViVanTai", tuNgayParameter, denNgayParameter, id_BenParameter, id_TuyenParameter, id_DonViParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoTongHop_SoGiaoThong_Result> sp_HD_BaoCaoTongHop_SoGiaoThong(string tuNgay, string denNgay, Nullable<int> id_So, string lstBen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_SoParameter = id_So.HasValue ?
                new ObjectParameter("Id_So", id_So) :
                new ObjectParameter("Id_So", typeof(int));
    
            var lstBenParameter = lstBen != null ?
                new ObjectParameter("lstBen", lstBen) :
                new ObjectParameter("lstBen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoTongHop_SoGiaoThong_Result>("sp_HD_BaoCaoTongHop_SoGiaoThong", tuNgayParameter, denNgayParameter, id_SoParameter, lstBenParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoTongHop_ToanQuoc_Result> sp_HD_BaoCaoTongHop_ToanQuoc(string tuNgay, string denNgay)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoTongHop_ToanQuoc_Result>("sp_HD_BaoCaoTongHop_ToanQuoc", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoTongHop_Tuyen_Result> sp_HD_BaoCaoTongHop_Tuyen(string tuNgay, string denNgay, Nullable<int> id_ben, Nullable<long> id_Tuyen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_benParameter = id_ben.HasValue ?
                new ObjectParameter("Id_ben", id_ben) :
                new ObjectParameter("Id_ben", typeof(int));
    
            var id_TuyenParameter = id_Tuyen.HasValue ?
                new ObjectParameter("Id_Tuyen", id_Tuyen) :
                new ObjectParameter("Id_Tuyen", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoTongHop_Tuyen_Result>("sp_HD_BaoCaoTongHop_Tuyen", tuNgayParameter, denNgayParameter, id_benParameter, id_TuyenParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoTongHop_Tuyen_DonViVanTai_Result> sp_HD_BaoCaoTongHop_Tuyen_DonViVanTai(string tuNgay, string denNgay, Nullable<int> id_ben, Nullable<long> id_Tuyen, Nullable<int> id_DonVi)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_benParameter = id_ben.HasValue ?
                new ObjectParameter("Id_ben", id_ben) :
                new ObjectParameter("Id_ben", typeof(int));
    
            var id_TuyenParameter = id_Tuyen.HasValue ?
                new ObjectParameter("Id_Tuyen", id_Tuyen) :
                new ObjectParameter("Id_Tuyen", typeof(long));
    
            var id_DonViParameter = id_DonVi.HasValue ?
                new ObjectParameter("Id_DonVi", id_DonVi) :
                new ObjectParameter("Id_DonVi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoTongHop_Tuyen_DonViVanTai_Result>("sp_HD_BaoCaoTongHop_Tuyen_DonViVanTai", tuNgayParameter, denNgayParameter, id_benParameter, id_TuyenParameter, id_DonViParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoTongHopTaiBen_Result> sp_HD_BaoCaoTongHopTaiBen(string tuNgay, string denNgay, Nullable<int> idBen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var idBenParameter = idBen.HasValue ?
                new ObjectParameter("IdBen", idBen) :
                new ObjectParameter("IdBen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoTongHopTaiBen_Result>("sp_HD_BaoCaoTongHopTaiBen", tuNgayParameter, denNgayParameter, idBenParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong_Result> sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong(Nullable<int> thang, Nullable<int> nam, Nullable<int> id_So)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var id_SoParameter = id_So.HasValue ?
                new ObjectParameter("Id_So", id_So) :
                new ObjectParameter("Id_So", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong_Result>("sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong", thangParameter, namParameter, id_SoParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong_NhieuTuyen_Result> sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong_NhieuTuyen(Nullable<int> thang, Nullable<int> nam, Nullable<int> id_So, string lstTuyen)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var id_SoParameter = id_So.HasValue ?
                new ObjectParameter("Id_So", id_So) :
                new ObjectParameter("Id_So", typeof(int));
    
            var lstTuyenParameter = lstTuyen != null ?
                new ObjectParameter("lstTuyen", lstTuyen) :
                new ObjectParameter("lstTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong_NhieuTuyen_Result>("sp_HD_BaoCaoXeChayNhoHon70_SoGiaoThong_NhieuTuyen", thangParameter, namParameter, id_SoParameter, lstTuyenParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeKhongHoatDong_DonViVanTai_Result> sp_HD_BaoCaoXeKhongHoatDong_DonViVanTai(string tuNgay, string denNgay, Nullable<int> id_Ben, Nullable<long> id_Tuyen, Nullable<int> id_DonVi)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_BenParameter = id_Ben.HasValue ?
                new ObjectParameter("Id_Ben", id_Ben) :
                new ObjectParameter("Id_Ben", typeof(int));
    
            var id_TuyenParameter = id_Tuyen.HasValue ?
                new ObjectParameter("Id_Tuyen", id_Tuyen) :
                new ObjectParameter("Id_Tuyen", typeof(long));
    
            var id_DonViParameter = id_DonVi.HasValue ?
                new ObjectParameter("Id_DonVi", id_DonVi) :
                new ObjectParameter("Id_DonVi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeKhongHoatDong_DonViVanTai_Result>("sp_HD_BaoCaoXeKhongHoatDong_DonViVanTai", tuNgayParameter, denNgayParameter, id_BenParameter, id_TuyenParameter, id_DonViParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeKhongHoatDong_ToanQuoc_Result> sp_HD_BaoCaoXeKhongHoatDong_ToanQuoc(string tuNgay, string denNgay, string lstSo)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var lstSoParameter = lstSo != null ?
                new ObjectParameter("lstSo", lstSo) :
                new ObjectParameter("lstSo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeKhongHoatDong_ToanQuoc_Result>("sp_HD_BaoCaoXeKhongHoatDong_ToanQuoc", tuNgayParameter, denNgayParameter, lstSoParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeKhongHoatDong_Tuyen_Result> sp_HD_BaoCaoXeKhongHoatDong_Tuyen(string tuNgay, string denNgay, Nullable<int> id_ben, Nullable<long> id_Tuyen, string lstCongTy)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_benParameter = id_ben.HasValue ?
                new ObjectParameter("Id_ben", id_ben) :
                new ObjectParameter("Id_ben", typeof(int));
    
            var id_TuyenParameter = id_Tuyen.HasValue ?
                new ObjectParameter("Id_Tuyen", id_Tuyen) :
                new ObjectParameter("Id_Tuyen", typeof(long));
    
            var lstCongTyParameter = lstCongTy != null ?
                new ObjectParameter("lstCongTy", lstCongTy) :
                new ObjectParameter("lstCongTy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeKhongHoatDong_Tuyen_Result>("sp_HD_BaoCaoXeKhongHoatDong_Tuyen", tuNgayParameter, denNgayParameter, id_benParameter, id_TuyenParameter, lstCongTyParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeKhongHoatDongTaiBen_Result> sp_HD_BaoCaoXeKhongHoatDongTaiBen(string tuNgay, string denNgay, Nullable<int> idBen, string lstTuyen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var idBenParameter = idBen.HasValue ?
                new ObjectParameter("IdBen", idBen) :
                new ObjectParameter("IdBen", typeof(int));
    
            var lstTuyenParameter = lstTuyen != null ?
                new ObjectParameter("lstTuyen", lstTuyen) :
                new ObjectParameter("lstTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeKhongHoatDongTaiBen_Result>("sp_HD_BaoCaoXeKhongHoatDongTaiBen", tuNgayParameter, denNgayParameter, idBenParameter, lstTuyenParameter);
        }
    
        public virtual ObjectResult<sp_NhatTrinhTheoXe_Result> sp_NhatTrinhTheoXe(string tuNgay, string denNgay, string bienSoXe, Nullable<long> idTuyen, Nullable<int> idCongTy)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var bienSoXeParameter = bienSoXe != null ?
                new ObjectParameter("BienSoXe", bienSoXe) :
                new ObjectParameter("BienSoXe", typeof(string));
    
            var idTuyenParameter = idTuyen.HasValue ?
                new ObjectParameter("IdTuyen", idTuyen) :
                new ObjectParameter("IdTuyen", typeof(long));
    
            var idCongTyParameter = idCongTy.HasValue ?
                new ObjectParameter("IdCongTy", idCongTy) :
                new ObjectParameter("IdCongTy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NhatTrinhTheoXe_Result>("sp_NhatTrinhTheoXe", tuNgayParameter, denNgayParameter, bienSoXeParameter, idTuyenParameter, idCongTyParameter);
        }
    
        public virtual ObjectResult<sp_HD_BaoCaoXeKhongHoatDong_SoGiaoThong_Result> sp_HD_BaoCaoXeKhongHoatDong_SoGiaoThong(string tuNgay, string denNgay, Nullable<int> id_So, string lstBen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var id_SoParameter = id_So.HasValue ?
                new ObjectParameter("Id_So", id_So) :
                new ObjectParameter("Id_So", typeof(int));
    
            var lstBenParameter = lstBen != null ?
                new ObjectParameter("lstBen", lstBen) :
                new ObjectParameter("lstBen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HD_BaoCaoXeKhongHoatDong_SoGiaoThong_Result>("sp_HD_BaoCaoXeKhongHoatDong_SoGiaoThong", tuNgayParameter, denNgayParameter, id_SoParameter, lstBenParameter);
        }
    }
}
