//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVT_ThongTinXe_beta
    {
        public long TX_BX_IdXe { get; set; }
        public Nullable<long> TX_IdXe { get; set; }
        public Nullable<int> TX_BX_SoGiuong { get; set; }
        public Nullable<int> TX_BX_SoGhe { get; set; }
        public Nullable<int> TX_BX_TongLuotVanChuyen { get; set; }
        public string TX_GioXuatBen { get; set; }
        public Nullable<double> TX_TanXuatNgay { get; set; }
    
        public virtual QLVT_ThongTinXe QLVT_ThongTinXe { get; set; }
    }
}
