//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVT_ThongTinTinh_So_Ben_TrangThai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLVT_ThongTinTinh_So_Ben_TrangThai()
        {
            this.QLVT_ThongTinBenXe = new HashSet<QLVT_ThongTinBenXe>();
            this.QLVT_ThongTinTinh_SoGiaoThong = new HashSet<QLVT_ThongTinTinh_SoGiaoThong>();
        }
    
        public int TS_TT_IdTrangThai { get; set; }
        public string TS_TT_TenTrangThai { get; set; }
        public string TS_TT_GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVT_ThongTinBenXe> QLVT_ThongTinBenXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVT_ThongTinTinh_SoGiaoThong> QLVT_ThongTinTinh_SoGiaoThong { get; set; }
    }
}
