//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVT_CapTuyenChoTinh_So
    {
        public long DS_IdCapTuyenTS { get; set; }
        public Nullable<long> LT_IdLuongTuyen { get; set; }
        public Nullable<int> TS_IdTinh_So { get; set; }
    
        public virtual QLVT_LuongTuyen QLVT_LuongTuyen { get; set; }
        public virtual QLVT_ThongTinTinh_SoGiaoThong QLVT_ThongTinTinh_SoGiaoThong { get; set; }
    }
}
