//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVT_LuongTuyen_TrangThai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLVT_LuongTuyen_TrangThai()
        {
            this.QLVT_LuongTuyen = new HashSet<QLVT_LuongTuyen>();
        }
    
        public int TT_IdTrangThaiTuyen { get; set; }
        public string TT_TenTrangThai { get; set; }
        public string TT_GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVT_LuongTuyen> QLVT_LuongTuyen { get; set; }
    }
}
