//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_UngDungTruyenTaiDuLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transfer_UngDungTruyenTaiDuLieu()
        {
            this.Transfer_NhatKyTruyenTaiDuLieu = new HashSet<Transfer_NhatKyTruyenTaiDuLieu>();
        }
    
        public long IDUngDungTruyenTaiDuLieu { get; set; }
        public long IDTaiKhoan { get; set; }
        public string MaUngDung { get; set; }
        public string MaBiMat { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
    
        public virtual HT_TaiKhoan HT_TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_NhatKyTruyenTaiDuLieu> Transfer_NhatKyTruyenTaiDuLieu { get; set; }
    }
}
