//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_LuongTuyen
    {
        public long LT_IdLuongTuyen { get; set; }
        public string LT_MaTuyen { get; set; }
        public Nullable<long> LT_DC_IdLuongTuyen { get; set; }
        public Nullable<int> LT_DC_IdBen_01 { get; set; }
        public Nullable<int> LT_DC_IdBen_02 { get; set; }
        public string TenTuyen { get; set; }
        public string LT_HanhTrinhChay { get; set; }
        public Nullable<double> LT_CuLy { get; set; }
        public Nullable<int> LT_LuuLuongQuyDinh { get; set; }
        public Nullable<int> TT_IdTrangThaiTuyen { get; set; }
        public string TT_TenTrangThai { get; set; }
        public Nullable<int> LT_PL_IdLuongTuyen { get; set; }
        public string LT_PL_TenLoai { get; set; }
    }
}
