//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ThongTinXe
    {
        public long TX_IdXe { get; set; }
        public string TX_BienSoXe { get; set; }
        public Nullable<int> TX_MaSoXe { get; set; }
        public Nullable<int> TX_BX_SoGhe { get; set; }
        public Nullable<int> TX_BX_SoGiuong { get; set; }
        public Nullable<int> TX_BX_TongLuotVanChuyen { get; set; }
        public string TX_GioXuatBen { get; set; }
        public int TS_IdTinh_So { get; set; }
        public Nullable<int> CT_IdCongTyVT { get; set; }
        public string TenCongTy { get; set; }
        public Nullable<int> TX_TT_IdTrangThaiXe { get; set; }
        public long LT_IdLuongTuyen { get; set; }
        public string LT_MaTuyen { get; set; }
        public string TenTuyen { get; set; }
        public Nullable<int> LT_DC_IdBen_01 { get; set; }
        public Nullable<int> LT_DC_IdBen_02 { get; set; }
        public string TX_TT_IdTenTrangThai { get; set; }
    }
}
