#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiKhoan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVanTai_2017")]
	public partial class HTDataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHT_NhatKy(HT_NhatKy instance);
    partial void UpdateHT_NhatKy(HT_NhatKy instance);
    partial void DeleteHT_NhatKy(HT_NhatKy instance);
    partial void InsertHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void UpdateHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void DeleteHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void InsertHT_PhanQuyen(HT_PhanQuyen instance);
    partial void UpdateHT_PhanQuyen(HT_PhanQuyen instance);
    partial void DeleteHT_PhanQuyen(HT_PhanQuyen instance);
    partial void InsertHT_Quyen(HT_Quyen instance);
    partial void UpdateHT_Quyen(HT_Quyen instance);
    partial void DeleteHT_Quyen(HT_Quyen instance);
    partial void InsertHT_TaiKhoan(HT_TaiKhoan instance);
    partial void UpdateHT_TaiKhoan(HT_TaiKhoan instance);
    partial void DeleteHT_TaiKhoan(HT_TaiKhoan instance);
    #endregion
		
		public HTDataClassDataContext() : 
				base(global::QuanLyTaiKhoan.Properties.Settings.Default.QLVanTai_2017ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HT_NhatKy> HT_NhatKies
		{
			get
			{
				return this.GetTable<HT_NhatKy>();
			}
		}
		
		public System.Data.Linq.Table<HT_ThongTinTaiKhoan> HT_ThongTinTaiKhoans
		{
			get
			{
				return this.GetTable<HT_ThongTinTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this.GetTable<HT_PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<HT_Quyen> HT_Quyens
		{
			get
			{
				return this.GetTable<HT_Quyen>();
			}
		}
		
		public System.Data.Linq.Table<HT_TaiKhoan> HT_TaiKhoans
		{
			get
			{
				return this.GetTable<HT_TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_NhatKy")]
	public partial class HT_NhatKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDNhatKy;
		
		private string _TenNhatKy;
		
		private string _LoaiNhatKy;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _ThoiGianTao;
		
		private System.Nullable<long> _IDTaiKhoan;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNhatKyChanging(long value);
    partial void OnIDNhatKyChanged();
    partial void OnTenNhatKyChanging(string value);
    partial void OnTenNhatKyChanged();
    partial void OnLoaiNhatKyChanging(string value);
    partial void OnLoaiNhatKyChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnThoiGianTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTaoChanged();
    partial void OnIDTaiKhoanChanging(System.Nullable<long> value);
    partial void OnIDTaiKhoanChanged();
    #endregion
		
		public HT_NhatKy()
		{
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhatKy", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDNhatKy
		{
			get
			{
				return this._IDNhatKy;
			}
			set
			{
				if ((this._IDNhatKy != value))
				{
					this.OnIDNhatKyChanging(value);
					this.SendPropertyChanging();
					this._IDNhatKy = value;
					this.SendPropertyChanged("IDNhatKy");
					this.OnIDNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhatKy", DbType="NVarChar(MAX)")]
		public string TenNhatKy
		{
			get
			{
				return this._TenNhatKy;
			}
			set
			{
				if ((this._TenNhatKy != value))
				{
					this.OnTenNhatKyChanging(value);
					this.SendPropertyChanging();
					this._TenNhatKy = value;
					this.SendPropertyChanged("TenNhatKy");
					this.OnTenNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNhatKy", DbType="NVarChar(MAX)")]
		public string LoaiNhatKy
		{
			get
			{
				return this._LoaiNhatKy;
			}
			set
			{
				if ((this._LoaiNhatKy != value))
				{
					this.OnLoaiNhatKyChanging(value);
					this.SendPropertyChanging();
					this._LoaiNhatKy = value;
					this.SendPropertyChanged("LoaiNhatKy");
					this.OnLoaiNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt")]
		public System.Nullable<long> IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_NhatKy", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_NhatKies.Remove(this);
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_NhatKies.Add(this);
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(Nullable<long>);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_ThongTinTaiKhoan")]
	public partial class HT_ThongTinTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private string _GhiChu;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public HT_ThongTinTaiKhoan()
		{
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_ThongTinTaiKhoan", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_ThongTinTaiKhoan = null;
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_ThongTinTaiKhoan = this;
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(long);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_PhanQuyen")]
	public partial class HT_PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private long _IDQuyen;
		
		private EntityRef<HT_Quyen> _HT_Quyen;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnIDQuyenChanging(long value);
    partial void OnIDQuyenChanged();
    #endregion
		
		public HT_PhanQuyen()
		{
			this._HT_Quyen = default(EntityRef<HT_Quyen>);
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					if (this._HT_Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_Quyen_HT_PhanQuyen", Storage="_HT_Quyen", ThisKey="IDQuyen", OtherKey="IDQuyen", IsForeignKey=true)]
		public HT_Quyen HT_Quyen
		{
			get
			{
				return this._HT_Quyen.Entity;
			}
			set
			{
				HT_Quyen previousValue = this._HT_Quyen.Entity;
				if (((previousValue != value) 
							|| (this._HT_Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_Quyen.Entity = null;
						previousValue.HT_PhanQuyens.Remove(this);
					}
					this._HT_Quyen.Entity = value;
					if ((value != null))
					{
						value.HT_PhanQuyens.Add(this);
						this._IDQuyen = value.IDQuyen;
					}
					else
					{
						this._IDQuyen = default(long);
					}
					this.SendPropertyChanged("HT_Quyen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_PhanQuyen", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_PhanQuyens.Remove(this);
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_PhanQuyens.Add(this);
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(long);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_Quyen")]
	public partial class HT_Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDQuyen;
		
		private string _TenQuyen;
		
		private string _NhomQuyen;
		
		private EntitySet<HT_PhanQuyen> _HT_PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDQuyenChanging(long value);
    partial void OnIDQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    partial void OnNhomQuyenChanging(string value);
    partial void OnNhomQuyenChanged();
    #endregion
		
		public HT_Quyen()
		{
			this._HT_PhanQuyens = new EntitySet<HT_PhanQuyen>(new Action<HT_PhanQuyen>(this.attach_HT_PhanQuyens), new Action<HT_PhanQuyen>(this.detach_HT_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomQuyen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NhomQuyen
		{
			get
			{
				return this._NhomQuyen;
			}
			set
			{
				if ((this._NhomQuyen != value))
				{
					this.OnNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._NhomQuyen = value;
					this.SendPropertyChanged("NhomQuyen");
					this.OnNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_Quyen_HT_PhanQuyen", Storage="_HT_PhanQuyens", ThisKey="IDQuyen", OtherKey="IDQuyen")]
		public EntitySet<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this._HT_PhanQuyens;
			}
			set
			{
				this._HT_PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_Quyen = this;
		}
		
		private void detach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_Quyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_TaiKhoan")]
	public partial class HT_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private System.DateTime _ThoiGianTao;
		
		private System.Nullable<long> _IDBen;
		
		private System.Nullable<long> _IDDonViVanTai;
		
		private System.Nullable<long> _IDSo;
		
		private EntitySet<HT_NhatKy> _HT_NhatKies;
		
		private EntityRef<HT_ThongTinTaiKhoan> _HT_ThongTinTaiKhoan;
		
		private EntitySet<HT_PhanQuyen> _HT_PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnThoiGianTaoChanging(System.DateTime value);
    partial void OnThoiGianTaoChanged();
    partial void OnIDBenChanging(System.Nullable<long> value);
    partial void OnIDBenChanged();
    partial void OnIDDonViVanTaiChanging(System.Nullable<long> value);
    partial void OnIDDonViVanTaiChanged();
    partial void OnIDSoChanging(System.Nullable<long> value);
    partial void OnIDSoChanged();
    #endregion
		
		public HT_TaiKhoan()
		{
			this._HT_NhatKies = new EntitySet<HT_NhatKy>(new Action<HT_NhatKy>(this.attach_HT_NhatKies), new Action<HT_NhatKy>(this.detach_HT_NhatKies));
			this._HT_ThongTinTaiKhoan = default(EntityRef<HT_ThongTinTaiKhoan>);
			this._HT_PhanQuyens = new EntitySet<HT_PhanQuyen>(new Action<HT_PhanQuyen>(this.attach_HT_PhanQuyens), new Action<HT_PhanQuyen>(this.detach_HT_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBen", DbType="BigInt")]
		public System.Nullable<long> IDBen
		{
			get
			{
				return this._IDBen;
			}
			set
			{
				if ((this._IDBen != value))
				{
					this.OnIDBenChanging(value);
					this.SendPropertyChanging();
					this._IDBen = value;
					this.SendPropertyChanged("IDBen");
					this.OnIDBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDonViVanTai", DbType="BigInt")]
		public System.Nullable<long> IDDonViVanTai
		{
			get
			{
				return this._IDDonViVanTai;
			}
			set
			{
				if ((this._IDDonViVanTai != value))
				{
					this.OnIDDonViVanTaiChanging(value);
					this.SendPropertyChanging();
					this._IDDonViVanTai = value;
					this.SendPropertyChanged("IDDonViVanTai");
					this.OnIDDonViVanTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSo", DbType="BigInt")]
		public System.Nullable<long> IDSo
		{
			get
			{
				return this._IDSo;
			}
			set
			{
				if ((this._IDSo != value))
				{
					this.OnIDSoChanging(value);
					this.SendPropertyChanging();
					this._IDSo = value;
					this.SendPropertyChanged("IDSo");
					this.OnIDSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_NhatKy", Storage="_HT_NhatKies", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan")]
		public EntitySet<HT_NhatKy> HT_NhatKies
		{
			get
			{
				return this._HT_NhatKies;
			}
			set
			{
				this._HT_NhatKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_ThongTinTaiKhoan", Storage="_HT_ThongTinTaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsUnique=true, IsForeignKey=false)]
		public HT_ThongTinTaiKhoan HT_ThongTinTaiKhoan
		{
			get
			{
				return this._HT_ThongTinTaiKhoan.Entity;
			}
			set
			{
				HT_ThongTinTaiKhoan previousValue = this._HT_ThongTinTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_ThongTinTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_ThongTinTaiKhoan.Entity = null;
						previousValue.HT_TaiKhoan = null;
					}
					this._HT_ThongTinTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_TaiKhoan = this;
					}
					this.SendPropertyChanged("HT_ThongTinTaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_PhanQuyen", Storage="_HT_PhanQuyens", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan")]
		public EntitySet<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this._HT_PhanQuyens;
			}
			set
			{
				this._HT_PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HT_NhatKies(HT_NhatKy entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = this;
		}
		
		private void detach_HT_NhatKies(HT_NhatKy entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = null;
		}
		
		private void attach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = this;
		}
		
		private void detach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = null;
		}
	}
}
#pragma warning restore 1591
