//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_HoatDongCapSo
    {
        public long Id { get; set; }
        public int Nam { get; set; }
        public int Thang { get; set; }
        public int TS_IdTinh_So { get; set; }
        public long LT_IdLuongTuyen { get; set; }
        public Nullable<int> SoChuyenKeHoach { get; set; }
        public Nullable<int> SoChuyenThucChay { get; set; }
        public Nullable<double> PhanTramThucHien { get; set; }
        public Nullable<int> SoKhach { get; set; }
    }
}
