//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVT_CongTyVanTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLVT_CongTyVanTai()
        {
            this.QLVT_DanhSachCapTuyenChoDN = new HashSet<QLVT_DanhSachCapTuyenChoDN>();
            this.QLVT_ThongTinXe = new HashSet<QLVT_ThongTinXe>();
        }
    
        public int CT_IdCongTyVT { get; set; }
        public string TenCongTy { get; set; }
        public Nullable<int> MaCongTy { get; set; }
        public Nullable<int> SoLuongXe { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> TS_IdTinh_So { get; set; }
        public Nullable<int> CT_TT_IdTrangThai { get; set; }
    
        public virtual QLVT_CongTyVanTai_TrangThai QLVT_CongTyVanTai_TrangThai { get; set; }
        public virtual QLVT_ThongTinTinh_SoGiaoThong QLVT_ThongTinTinh_SoGiaoThong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVT_DanhSachCapTuyenChoDN> QLVT_DanhSachCapTuyenChoDN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVT_ThongTinXe> QLVT_ThongTinXe { get; set; }
    }
}
