//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVT_ThongTinXe_TrangThaiXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLVT_ThongTinXe_TrangThaiXe()
        {
            this.QLVT_ThongTinXe = new HashSet<QLVT_ThongTinXe>();
        }
    
        public int TX_TT_IdTrangThaiXe { get; set; }
        public string TX_TT_IdTenTrangThai { get; set; }
        public string TX_TT_GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVT_ThongTinXe> QLVT_ThongTinXe { get; set; }
    }
}
