//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_NhatKyTruyenTaiDuLieu
    {
        public long IDNhatKyTruyenTaiDuLieu { get; set; }
        public long IDUngDungTruyenTaiDuLieu { get; set; }
        public string DuLieu { get; set; }
        public string ThongTinThem { get; set; }
        public Nullable<long> IDNhatTrinhXe { get; set; }
    
        public virtual NhatTrinhXe NhatTrinhXe { get; set; }
        public virtual Transfer_UngDungTruyenTaiDuLieu Transfer_UngDungTruyenTaiDuLieu { get; set; }
    }
}
