#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiKhoan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVanTai_2017")]
	public partial class HTDataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHT_NhatKy(HT_NhatKy instance);
    partial void UpdateHT_NhatKy(HT_NhatKy instance);
    partial void DeleteHT_NhatKy(HT_NhatKy instance);
    partial void InsertHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void UpdateHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void DeleteHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void InsertHT_PhanQuyen(HT_PhanQuyen instance);
    partial void UpdateHT_PhanQuyen(HT_PhanQuyen instance);
    partial void DeleteHT_PhanQuyen(HT_PhanQuyen instance);
    partial void InsertHT_Quyen(HT_Quyen instance);
    partial void UpdateHT_Quyen(HT_Quyen instance);
    partial void DeleteHT_Quyen(HT_Quyen instance);
    partial void InsertHT_TaiKhoan(HT_TaiKhoan instance);
    partial void UpdateHT_TaiKhoan(HT_TaiKhoan instance);
    partial void DeleteHT_TaiKhoan(HT_TaiKhoan instance);
    partial void InsertQLVT_ThongTinTinh_SoGiaoThong(QLVT_ThongTinTinh_SoGiaoThong instance);
    partial void UpdateQLVT_ThongTinTinh_SoGiaoThong(QLVT_ThongTinTinh_SoGiaoThong instance);
    partial void DeleteQLVT_ThongTinTinh_SoGiaoThong(QLVT_ThongTinTinh_SoGiaoThong instance);
    partial void InsertQLVT_ThongTinBenXe(QLVT_ThongTinBenXe instance);
    partial void UpdateQLVT_ThongTinBenXe(QLVT_ThongTinBenXe instance);
    partial void DeleteQLVT_ThongTinBenXe(QLVT_ThongTinBenXe instance);
    partial void InsertQLVT_CongTyVanTai(QLVT_CongTyVanTai instance);
    partial void UpdateQLVT_CongTyVanTai(QLVT_CongTyVanTai instance);
    partial void DeleteQLVT_CongTyVanTai(QLVT_CongTyVanTai instance);
    #endregion
		
		public HTDataClassDataContext() : 
				base(global::QuanLyTaiKhoan.Properties.Settings.Default.QLVanTai_2017ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTDataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HT_NhatKy> HT_NhatKies
		{
			get
			{
				return this.GetTable<HT_NhatKy>();
			}
		}
		
		public System.Data.Linq.Table<HT_ThongTinTaiKhoan> HT_ThongTinTaiKhoans
		{
			get
			{
				return this.GetTable<HT_ThongTinTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this.GetTable<HT_PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<HT_Quyen> HT_Quyens
		{
			get
			{
				return this.GetTable<HT_Quyen>();
			}
		}
		
		public System.Data.Linq.Table<HT_TaiKhoan> HT_TaiKhoans
		{
			get
			{
				return this.GetTable<HT_TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_ThongTinTinh_SoGiaoThong> QLVT_ThongTinTinh_SoGiaoThongs
		{
			get
			{
				return this.GetTable<QLVT_ThongTinTinh_SoGiaoThong>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_ThongTinBenXe> QLVT_ThongTinBenXes
		{
			get
			{
				return this.GetTable<QLVT_ThongTinBenXe>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_CongTyVanTai> QLVT_CongTyVanTais
		{
			get
			{
				return this.GetTable<QLVT_CongTyVanTai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_NhatKy")]
	public partial class HT_NhatKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDNhatKy;
		
		private string _TenNhatKy;
		
		private string _LoaiNhatKy;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _ThoiGianTao;
		
		private System.Nullable<long> _IDTaiKhoan;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNhatKyChanging(long value);
    partial void OnIDNhatKyChanged();
    partial void OnTenNhatKyChanging(string value);
    partial void OnTenNhatKyChanged();
    partial void OnLoaiNhatKyChanging(string value);
    partial void OnLoaiNhatKyChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnThoiGianTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTaoChanged();
    partial void OnIDTaiKhoanChanging(System.Nullable<long> value);
    partial void OnIDTaiKhoanChanged();
    #endregion
		
		public HT_NhatKy()
		{
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhatKy", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDNhatKy
		{
			get
			{
				return this._IDNhatKy;
			}
			set
			{
				if ((this._IDNhatKy != value))
				{
					this.OnIDNhatKyChanging(value);
					this.SendPropertyChanging();
					this._IDNhatKy = value;
					this.SendPropertyChanged("IDNhatKy");
					this.OnIDNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhatKy", DbType="NVarChar(MAX)")]
		public string TenNhatKy
		{
			get
			{
				return this._TenNhatKy;
			}
			set
			{
				if ((this._TenNhatKy != value))
				{
					this.OnTenNhatKyChanging(value);
					this.SendPropertyChanging();
					this._TenNhatKy = value;
					this.SendPropertyChanged("TenNhatKy");
					this.OnTenNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNhatKy", DbType="NVarChar(MAX)")]
		public string LoaiNhatKy
		{
			get
			{
				return this._LoaiNhatKy;
			}
			set
			{
				if ((this._LoaiNhatKy != value))
				{
					this.OnLoaiNhatKyChanging(value);
					this.SendPropertyChanging();
					this._LoaiNhatKy = value;
					this.SendPropertyChanged("LoaiNhatKy");
					this.OnLoaiNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt")]
		public System.Nullable<long> IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_NhatKy", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_NhatKies.Remove(this);
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_NhatKies.Add(this);
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(Nullable<long>);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_ThongTinTaiKhoan")]
	public partial class HT_ThongTinTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private string _GhiChu;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public HT_ThongTinTaiKhoan()
		{
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_ThongTinTaiKhoan", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_ThongTinTaiKhoan = null;
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_ThongTinTaiKhoan = this;
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(long);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_PhanQuyen")]
	public partial class HT_PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nhom;
		
		private long _IDQuyen;
		
		private EntityRef<HT_Quyen> _HT_Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNhomChanging(string value);
    partial void OnNhomChanged();
    partial void OnIDQuyenChanging(long value);
    partial void OnIDQuyenChanged();
    #endregion
		
		public HT_PhanQuyen()
		{
			this._HT_Quyen = default(EntityRef<HT_Quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this.OnNhomChanging(value);
					this.SendPropertyChanging();
					this._Nhom = value;
					this.SendPropertyChanged("Nhom");
					this.OnNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					if (this._HT_Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_Quyen_HT_PhanQuyen", Storage="_HT_Quyen", ThisKey="IDQuyen", OtherKey="IDQuyen", IsForeignKey=true)]
		public HT_Quyen HT_Quyen
		{
			get
			{
				return this._HT_Quyen.Entity;
			}
			set
			{
				HT_Quyen previousValue = this._HT_Quyen.Entity;
				if (((previousValue != value) 
							|| (this._HT_Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_Quyen.Entity = null;
						previousValue.HT_PhanQuyens.Remove(this);
					}
					this._HT_Quyen.Entity = value;
					if ((value != null))
					{
						value.HT_PhanQuyens.Add(this);
						this._IDQuyen = value.IDQuyen;
					}
					else
					{
						this._IDQuyen = default(long);
					}
					this.SendPropertyChanged("HT_Quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_Quyen")]
	public partial class HT_Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDQuyen;
		
		private string _TenQuyen;
		
		private string _NhomQuyen;
		
		private string _Rule;
		
		private EntitySet<HT_PhanQuyen> _HT_PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDQuyenChanging(long value);
    partial void OnIDQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    partial void OnNhomQuyenChanging(string value);
    partial void OnNhomQuyenChanged();
    partial void OnRuleChanging(string value);
    partial void OnRuleChanged();
    #endregion
		
		public HT_Quyen()
		{
			this._HT_PhanQuyens = new EntitySet<HT_PhanQuyen>(new Action<HT_PhanQuyen>(this.attach_HT_PhanQuyens), new Action<HT_PhanQuyen>(this.detach_HT_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomQuyen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NhomQuyen
		{
			get
			{
				return this._NhomQuyen;
			}
			set
			{
				if ((this._NhomQuyen != value))
				{
					this.OnNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._NhomQuyen = value;
					this.SendPropertyChanged("NhomQuyen");
					this.OnNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rule]", Storage="_Rule", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Rule
		{
			get
			{
				return this._Rule;
			}
			set
			{
				if ((this._Rule != value))
				{
					this.OnRuleChanging(value);
					this.SendPropertyChanging();
					this._Rule = value;
					this.SendPropertyChanged("Rule");
					this.OnRuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_Quyen_HT_PhanQuyen", Storage="_HT_PhanQuyens", ThisKey="IDQuyen", OtherKey="IDQuyen")]
		public EntitySet<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this._HT_PhanQuyens;
			}
			set
			{
				this._HT_PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_Quyen = this;
		}
		
		private void detach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_Quyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_TaiKhoan")]
	public partial class HT_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private System.DateTime _ThoiGianTao;
		
		private System.Nullable<long> _IDBen;
		
		private System.Nullable<long> _IDDonViVanTai;
		
		private System.Nullable<long> _IDSo;
		
		private EntitySet<HT_NhatKy> _HT_NhatKies;
		
		private EntityRef<HT_ThongTinTaiKhoan> _HT_ThongTinTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnThoiGianTaoChanging(System.DateTime value);
    partial void OnThoiGianTaoChanged();
    partial void OnIDBenChanging(System.Nullable<long> value);
    partial void OnIDBenChanged();
    partial void OnIDDonViVanTaiChanging(System.Nullable<long> value);
    partial void OnIDDonViVanTaiChanged();
    partial void OnIDSoChanging(System.Nullable<long> value);
    partial void OnIDSoChanged();
    #endregion
		
		public HT_TaiKhoan()
		{
			this._HT_NhatKies = new EntitySet<HT_NhatKy>(new Action<HT_NhatKy>(this.attach_HT_NhatKies), new Action<HT_NhatKy>(this.detach_HT_NhatKies));
			this._HT_ThongTinTaiKhoan = default(EntityRef<HT_ThongTinTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBen", DbType="BigInt")]
		public System.Nullable<long> IDBen
		{
			get
			{
				return this._IDBen;
			}
			set
			{
				if ((this._IDBen != value))
				{
					this.OnIDBenChanging(value);
					this.SendPropertyChanging();
					this._IDBen = value;
					this.SendPropertyChanged("IDBen");
					this.OnIDBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDonViVanTai", DbType="BigInt")]
		public System.Nullable<long> IDDonViVanTai
		{
			get
			{
				return this._IDDonViVanTai;
			}
			set
			{
				if ((this._IDDonViVanTai != value))
				{
					this.OnIDDonViVanTaiChanging(value);
					this.SendPropertyChanging();
					this._IDDonViVanTai = value;
					this.SendPropertyChanged("IDDonViVanTai");
					this.OnIDDonViVanTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSo", DbType="BigInt")]
		public System.Nullable<long> IDSo
		{
			get
			{
				return this._IDSo;
			}
			set
			{
				if ((this._IDSo != value))
				{
					this.OnIDSoChanging(value);
					this.SendPropertyChanging();
					this._IDSo = value;
					this.SendPropertyChanged("IDSo");
					this.OnIDSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_NhatKy", Storage="_HT_NhatKies", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan")]
		public EntitySet<HT_NhatKy> HT_NhatKies
		{
			get
			{
				return this._HT_NhatKies;
			}
			set
			{
				this._HT_NhatKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_ThongTinTaiKhoan", Storage="_HT_ThongTinTaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsUnique=true, IsForeignKey=false)]
		public HT_ThongTinTaiKhoan HT_ThongTinTaiKhoan
		{
			get
			{
				return this._HT_ThongTinTaiKhoan.Entity;
			}
			set
			{
				HT_ThongTinTaiKhoan previousValue = this._HT_ThongTinTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_ThongTinTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_ThongTinTaiKhoan.Entity = null;
						previousValue.HT_TaiKhoan = null;
					}
					this._HT_ThongTinTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_TaiKhoan = this;
					}
					this.SendPropertyChanged("HT_ThongTinTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HT_NhatKies(HT_NhatKy entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = this;
		}
		
		private void detach_HT_NhatKies(HT_NhatKy entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_ThongTinTinh_SoGiaoThong")]
	public partial class QLVT_ThongTinTinh_SoGiaoThong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TS_IdTinh_So;
		
		private System.Nullable<int> _TS_IdMaTinh;
		
		private string _TS_TenTinh;
		
		private System.Nullable<int> _TS_TT_IdTrangThai;
		
		private string _GiamDocSo;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private EntitySet<QLVT_ThongTinBenXe> _QLVT_ThongTinBenXes;
		
		private EntitySet<QLVT_CongTyVanTai> _QLVT_CongTyVanTais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTS_IdTinh_SoChanging(int value);
    partial void OnTS_IdTinh_SoChanged();
    partial void OnTS_IdMaTinhChanging(System.Nullable<int> value);
    partial void OnTS_IdMaTinhChanged();
    partial void OnTS_TenTinhChanging(string value);
    partial void OnTS_TenTinhChanged();
    partial void OnTS_TT_IdTrangThaiChanging(System.Nullable<int> value);
    partial void OnTS_TT_IdTrangThaiChanged();
    partial void OnGiamDocSoChanging(string value);
    partial void OnGiamDocSoChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public QLVT_ThongTinTinh_SoGiaoThong()
		{
			this._QLVT_ThongTinBenXes = new EntitySet<QLVT_ThongTinBenXe>(new Action<QLVT_ThongTinBenXe>(this.attach_QLVT_ThongTinBenXes), new Action<QLVT_ThongTinBenXe>(this.detach_QLVT_ThongTinBenXes));
			this._QLVT_CongTyVanTais = new EntitySet<QLVT_CongTyVanTai>(new Action<QLVT_CongTyVanTai>(this.attach_QLVT_CongTyVanTais), new Action<QLVT_CongTyVanTai>(this.detach_QLVT_CongTyVanTais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdTinh_So", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TS_IdTinh_So
		{
			get
			{
				return this._TS_IdTinh_So;
			}
			set
			{
				if ((this._TS_IdTinh_So != value))
				{
					this.OnTS_IdTinh_SoChanging(value);
					this.SendPropertyChanging();
					this._TS_IdTinh_So = value;
					this.SendPropertyChanged("TS_IdTinh_So");
					this.OnTS_IdTinh_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdMaTinh", DbType="Int")]
		public System.Nullable<int> TS_IdMaTinh
		{
			get
			{
				return this._TS_IdMaTinh;
			}
			set
			{
				if ((this._TS_IdMaTinh != value))
				{
					this.OnTS_IdMaTinhChanging(value);
					this.SendPropertyChanging();
					this._TS_IdMaTinh = value;
					this.SendPropertyChanged("TS_IdMaTinh");
					this.OnTS_IdMaTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_TenTinh", DbType="NVarChar(256)")]
		public string TS_TenTinh
		{
			get
			{
				return this._TS_TenTinh;
			}
			set
			{
				if ((this._TS_TenTinh != value))
				{
					this.OnTS_TenTinhChanging(value);
					this.SendPropertyChanging();
					this._TS_TenTinh = value;
					this.SendPropertyChanged("TS_TenTinh");
					this.OnTS_TenTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_TT_IdTrangThai", DbType="Int")]
		public System.Nullable<int> TS_TT_IdTrangThai
		{
			get
			{
				return this._TS_TT_IdTrangThai;
			}
			set
			{
				if ((this._TS_TT_IdTrangThai != value))
				{
					this.OnTS_TT_IdTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TS_TT_IdTrangThai = value;
					this.SendPropertyChanged("TS_TT_IdTrangThai");
					this.OnTS_TT_IdTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamDocSo", DbType="NVarChar(50)")]
		public string GiamDocSo
		{
			get
			{
				return this._GiamDocSo;
			}
			set
			{
				if ((this._GiamDocSo != value))
				{
					this.OnGiamDocSoChanging(value);
					this.SendPropertyChanging();
					this._GiamDocSo = value;
					this.SendPropertyChanged("GiamDocSo");
					this.OnGiamDocSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLVT_ThongTinTinh_SoGiaoThong_QLVT_ThongTinBenXe", Storage="_QLVT_ThongTinBenXes", ThisKey="TS_IdTinh_So", OtherKey="TS_IdTinh_So")]
		public EntitySet<QLVT_ThongTinBenXe> QLVT_ThongTinBenXes
		{
			get
			{
				return this._QLVT_ThongTinBenXes;
			}
			set
			{
				this._QLVT_ThongTinBenXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLVT_ThongTinTinh_SoGiaoThong_QLVT_CongTyVanTai", Storage="_QLVT_CongTyVanTais", ThisKey="TS_IdTinh_So", OtherKey="TS_IdTinh_So")]
		public EntitySet<QLVT_CongTyVanTai> QLVT_CongTyVanTais
		{
			get
			{
				return this._QLVT_CongTyVanTais;
			}
			set
			{
				this._QLVT_CongTyVanTais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QLVT_ThongTinBenXes(QLVT_ThongTinBenXe entity)
		{
			this.SendPropertyChanging();
			entity.QLVT_ThongTinTinh_SoGiaoThong = this;
		}
		
		private void detach_QLVT_ThongTinBenXes(QLVT_ThongTinBenXe entity)
		{
			this.SendPropertyChanging();
			entity.QLVT_ThongTinTinh_SoGiaoThong = null;
		}
		
		private void attach_QLVT_CongTyVanTais(QLVT_CongTyVanTai entity)
		{
			this.SendPropertyChanging();
			entity.QLVT_ThongTinTinh_SoGiaoThong = this;
		}
		
		private void detach_QLVT_CongTyVanTais(QLVT_CongTyVanTai entity)
		{
			this.SendPropertyChanging();
			entity.QLVT_ThongTinTinh_SoGiaoThong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_ThongTinBenXe")]
	public partial class QLVT_ThongTinBenXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BX_IdBenXe;
		
		private string _TenBenXe;
		
		private System.Nullable<int> _MaBen;
		
		private System.Nullable<int> _TS_IdTinh_So;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _CoQuanQuanLy;
		
		private System.Nullable<double> _TongDienTich;
		
		private System.Nullable<double> _DienTich_XeKhach;
		
		private System.Nullable<double> _DienTich_PhuongTienKhac;
		
		private System.Nullable<double> _DienTich_NhaCho;
		
		private System.Nullable<int> _LoaiBenXe;
		
		private System.Nullable<int> _SoTuyenQuyHoach;
		
		private System.Nullable<int> _SoLuotXuatBenQuyHoach;
		
		private System.Nullable<int> _SoLuotXuatBenDangKy;
		
		private string _GhiChu;
		
		private System.Nullable<int> _TS_TT_IdTrangThai;
		
		private EntityRef<QLVT_ThongTinTinh_SoGiaoThong> _QLVT_ThongTinTinh_SoGiaoThong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBX_IdBenXeChanging(int value);
    partial void OnBX_IdBenXeChanged();
    partial void OnTenBenXeChanging(string value);
    partial void OnTenBenXeChanged();
    partial void OnMaBenChanging(System.Nullable<int> value);
    partial void OnMaBenChanged();
    partial void OnTS_IdTinh_SoChanging(System.Nullable<int> value);
    partial void OnTS_IdTinh_SoChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCoQuanQuanLyChanging(string value);
    partial void OnCoQuanQuanLyChanged();
    partial void OnTongDienTichChanging(System.Nullable<double> value);
    partial void OnTongDienTichChanged();
    partial void OnDienTich_XeKhachChanging(System.Nullable<double> value);
    partial void OnDienTich_XeKhachChanged();
    partial void OnDienTich_PhuongTienKhacChanging(System.Nullable<double> value);
    partial void OnDienTich_PhuongTienKhacChanged();
    partial void OnDienTich_NhaChoChanging(System.Nullable<double> value);
    partial void OnDienTich_NhaChoChanged();
    partial void OnLoaiBenXeChanging(System.Nullable<int> value);
    partial void OnLoaiBenXeChanged();
    partial void OnSoTuyenQuyHoachChanging(System.Nullable<int> value);
    partial void OnSoTuyenQuyHoachChanged();
    partial void OnSoLuotXuatBenQuyHoachChanging(System.Nullable<int> value);
    partial void OnSoLuotXuatBenQuyHoachChanged();
    partial void OnSoLuotXuatBenDangKyChanging(System.Nullable<int> value);
    partial void OnSoLuotXuatBenDangKyChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTS_TT_IdTrangThaiChanging(System.Nullable<int> value);
    partial void OnTS_TT_IdTrangThaiChanged();
    #endregion
		
		public QLVT_ThongTinBenXe()
		{
			this._QLVT_ThongTinTinh_SoGiaoThong = default(EntityRef<QLVT_ThongTinTinh_SoGiaoThong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BX_IdBenXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BX_IdBenXe
		{
			get
			{
				return this._BX_IdBenXe;
			}
			set
			{
				if ((this._BX_IdBenXe != value))
				{
					this.OnBX_IdBenXeChanging(value);
					this.SendPropertyChanging();
					this._BX_IdBenXe = value;
					this.SendPropertyChanged("BX_IdBenXe");
					this.OnBX_IdBenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenXe", DbType="NVarChar(512)")]
		public string TenBenXe
		{
			get
			{
				return this._TenBenXe;
			}
			set
			{
				if ((this._TenBenXe != value))
				{
					this.OnTenBenXeChanging(value);
					this.SendPropertyChanging();
					this._TenBenXe = value;
					this.SendPropertyChanged("TenBenXe");
					this.OnTenBenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBen", DbType="Int")]
		public System.Nullable<int> MaBen
		{
			get
			{
				return this._MaBen;
			}
			set
			{
				if ((this._MaBen != value))
				{
					this.OnMaBenChanging(value);
					this.SendPropertyChanging();
					this._MaBen = value;
					this.SendPropertyChanged("MaBen");
					this.OnMaBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdTinh_So", DbType="Int")]
		public System.Nullable<int> TS_IdTinh_So
		{
			get
			{
				return this._TS_IdTinh_So;
			}
			set
			{
				if ((this._TS_IdTinh_So != value))
				{
					if (this._QLVT_ThongTinTinh_SoGiaoThong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTS_IdTinh_SoChanging(value);
					this.SendPropertyChanging();
					this._TS_IdTinh_So = value;
					this.SendPropertyChanged("TS_IdTinh_So");
					this.OnTS_IdTinh_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(16)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuanQuanLy", DbType="NVarChar(MAX)")]
		public string CoQuanQuanLy
		{
			get
			{
				return this._CoQuanQuanLy;
			}
			set
			{
				if ((this._CoQuanQuanLy != value))
				{
					this.OnCoQuanQuanLyChanging(value);
					this.SendPropertyChanging();
					this._CoQuanQuanLy = value;
					this.SendPropertyChanged("CoQuanQuanLy");
					this.OnCoQuanQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDienTich", DbType="Float")]
		public System.Nullable<double> TongDienTich
		{
			get
			{
				return this._TongDienTich;
			}
			set
			{
				if ((this._TongDienTich != value))
				{
					this.OnTongDienTichChanging(value);
					this.SendPropertyChanging();
					this._TongDienTich = value;
					this.SendPropertyChanged("TongDienTich");
					this.OnTongDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_XeKhach", DbType="Float")]
		public System.Nullable<double> DienTich_XeKhach
		{
			get
			{
				return this._DienTich_XeKhach;
			}
			set
			{
				if ((this._DienTich_XeKhach != value))
				{
					this.OnDienTich_XeKhachChanging(value);
					this.SendPropertyChanging();
					this._DienTich_XeKhach = value;
					this.SendPropertyChanged("DienTich_XeKhach");
					this.OnDienTich_XeKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_PhuongTienKhac", DbType="Float")]
		public System.Nullable<double> DienTich_PhuongTienKhac
		{
			get
			{
				return this._DienTich_PhuongTienKhac;
			}
			set
			{
				if ((this._DienTich_PhuongTienKhac != value))
				{
					this.OnDienTich_PhuongTienKhacChanging(value);
					this.SendPropertyChanging();
					this._DienTich_PhuongTienKhac = value;
					this.SendPropertyChanged("DienTich_PhuongTienKhac");
					this.OnDienTich_PhuongTienKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_NhaCho", DbType="Float")]
		public System.Nullable<double> DienTich_NhaCho
		{
			get
			{
				return this._DienTich_NhaCho;
			}
			set
			{
				if ((this._DienTich_NhaCho != value))
				{
					this.OnDienTich_NhaChoChanging(value);
					this.SendPropertyChanging();
					this._DienTich_NhaCho = value;
					this.SendPropertyChanged("DienTich_NhaCho");
					this.OnDienTich_NhaChoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBenXe", DbType="Int")]
		public System.Nullable<int> LoaiBenXe
		{
			get
			{
				return this._LoaiBenXe;
			}
			set
			{
				if ((this._LoaiBenXe != value))
				{
					this.OnLoaiBenXeChanging(value);
					this.SendPropertyChanging();
					this._LoaiBenXe = value;
					this.SendPropertyChanged("LoaiBenXe");
					this.OnLoaiBenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTuyenQuyHoach", DbType="Int")]
		public System.Nullable<int> SoTuyenQuyHoach
		{
			get
			{
				return this._SoTuyenQuyHoach;
			}
			set
			{
				if ((this._SoTuyenQuyHoach != value))
				{
					this.OnSoTuyenQuyHoachChanging(value);
					this.SendPropertyChanging();
					this._SoTuyenQuyHoach = value;
					this.SendPropertyChanged("SoTuyenQuyHoach");
					this.OnSoTuyenQuyHoachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuotXuatBenQuyHoach", DbType="Int")]
		public System.Nullable<int> SoLuotXuatBenQuyHoach
		{
			get
			{
				return this._SoLuotXuatBenQuyHoach;
			}
			set
			{
				if ((this._SoLuotXuatBenQuyHoach != value))
				{
					this.OnSoLuotXuatBenQuyHoachChanging(value);
					this.SendPropertyChanging();
					this._SoLuotXuatBenQuyHoach = value;
					this.SendPropertyChanged("SoLuotXuatBenQuyHoach");
					this.OnSoLuotXuatBenQuyHoachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuotXuatBenDangKy", DbType="Int")]
		public System.Nullable<int> SoLuotXuatBenDangKy
		{
			get
			{
				return this._SoLuotXuatBenDangKy;
			}
			set
			{
				if ((this._SoLuotXuatBenDangKy != value))
				{
					this.OnSoLuotXuatBenDangKyChanging(value);
					this.SendPropertyChanging();
					this._SoLuotXuatBenDangKy = value;
					this.SendPropertyChanged("SoLuotXuatBenDangKy");
					this.OnSoLuotXuatBenDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_TT_IdTrangThai", DbType="Int")]
		public System.Nullable<int> TS_TT_IdTrangThai
		{
			get
			{
				return this._TS_TT_IdTrangThai;
			}
			set
			{
				if ((this._TS_TT_IdTrangThai != value))
				{
					this.OnTS_TT_IdTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TS_TT_IdTrangThai = value;
					this.SendPropertyChanged("TS_TT_IdTrangThai");
					this.OnTS_TT_IdTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLVT_ThongTinTinh_SoGiaoThong_QLVT_ThongTinBenXe", Storage="_QLVT_ThongTinTinh_SoGiaoThong", ThisKey="TS_IdTinh_So", OtherKey="TS_IdTinh_So", IsForeignKey=true)]
		public QLVT_ThongTinTinh_SoGiaoThong QLVT_ThongTinTinh_SoGiaoThong
		{
			get
			{
				return this._QLVT_ThongTinTinh_SoGiaoThong.Entity;
			}
			set
			{
				QLVT_ThongTinTinh_SoGiaoThong previousValue = this._QLVT_ThongTinTinh_SoGiaoThong.Entity;
				if (((previousValue != value) 
							|| (this._QLVT_ThongTinTinh_SoGiaoThong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QLVT_ThongTinTinh_SoGiaoThong.Entity = null;
						previousValue.QLVT_ThongTinBenXes.Remove(this);
					}
					this._QLVT_ThongTinTinh_SoGiaoThong.Entity = value;
					if ((value != null))
					{
						value.QLVT_ThongTinBenXes.Add(this);
						this._TS_IdTinh_So = value.TS_IdTinh_So;
					}
					else
					{
						this._TS_IdTinh_So = default(Nullable<int>);
					}
					this.SendPropertyChanged("QLVT_ThongTinTinh_SoGiaoThong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_CongTyVanTai")]
	public partial class QLVT_CongTyVanTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CT_IdCongTyVT;
		
		private string _TenCongTy;
		
		private System.Nullable<int> _MaCongTy;
		
		private System.Nullable<int> _SoLuongXe;
		
		private string _DiaChi;
		
		private System.Nullable<int> _TS_IdTinh_So;
		
		private System.Nullable<int> _CT_TT_IdTrangThai;
		
		private EntityRef<QLVT_ThongTinTinh_SoGiaoThong> _QLVT_ThongTinTinh_SoGiaoThong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCT_IdCongTyVTChanging(int value);
    partial void OnCT_IdCongTyVTChanged();
    partial void OnTenCongTyChanging(string value);
    partial void OnTenCongTyChanged();
    partial void OnMaCongTyChanging(System.Nullable<int> value);
    partial void OnMaCongTyChanged();
    partial void OnSoLuongXeChanging(System.Nullable<int> value);
    partial void OnSoLuongXeChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTS_IdTinh_SoChanging(System.Nullable<int> value);
    partial void OnTS_IdTinh_SoChanged();
    partial void OnCT_TT_IdTrangThaiChanging(System.Nullable<int> value);
    partial void OnCT_TT_IdTrangThaiChanged();
    #endregion
		
		public QLVT_CongTyVanTai()
		{
			this._QLVT_ThongTinTinh_SoGiaoThong = default(EntityRef<QLVT_ThongTinTinh_SoGiaoThong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_IdCongTyVT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CT_IdCongTyVT
		{
			get
			{
				return this._CT_IdCongTyVT;
			}
			set
			{
				if ((this._CT_IdCongTyVT != value))
				{
					this.OnCT_IdCongTyVTChanging(value);
					this.SendPropertyChanging();
					this._CT_IdCongTyVT = value;
					this.SendPropertyChanged("CT_IdCongTyVT");
					this.OnCT_IdCongTyVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTy", DbType="NVarChar(256)")]
		public string TenCongTy
		{
			get
			{
				return this._TenCongTy;
			}
			set
			{
				if ((this._TenCongTy != value))
				{
					this.OnTenCongTyChanging(value);
					this.SendPropertyChanging();
					this._TenCongTy = value;
					this.SendPropertyChanged("TenCongTy");
					this.OnTenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTy", DbType="Int")]
		public System.Nullable<int> MaCongTy
		{
			get
			{
				return this._MaCongTy;
			}
			set
			{
				if ((this._MaCongTy != value))
				{
					this.OnMaCongTyChanging(value);
					this.SendPropertyChanging();
					this._MaCongTy = value;
					this.SendPropertyChanged("MaCongTy");
					this.OnMaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongXe", DbType="Int")]
		public System.Nullable<int> SoLuongXe
		{
			get
			{
				return this._SoLuongXe;
			}
			set
			{
				if ((this._SoLuongXe != value))
				{
					this.OnSoLuongXeChanging(value);
					this.SendPropertyChanging();
					this._SoLuongXe = value;
					this.SendPropertyChanged("SoLuongXe");
					this.OnSoLuongXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdTinh_So", DbType="Int")]
		public System.Nullable<int> TS_IdTinh_So
		{
			get
			{
				return this._TS_IdTinh_So;
			}
			set
			{
				if ((this._TS_IdTinh_So != value))
				{
					if (this._QLVT_ThongTinTinh_SoGiaoThong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTS_IdTinh_SoChanging(value);
					this.SendPropertyChanging();
					this._TS_IdTinh_So = value;
					this.SendPropertyChanged("TS_IdTinh_So");
					this.OnTS_IdTinh_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_TT_IdTrangThai", DbType="Int")]
		public System.Nullable<int> CT_TT_IdTrangThai
		{
			get
			{
				return this._CT_TT_IdTrangThai;
			}
			set
			{
				if ((this._CT_TT_IdTrangThai != value))
				{
					this.OnCT_TT_IdTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._CT_TT_IdTrangThai = value;
					this.SendPropertyChanged("CT_TT_IdTrangThai");
					this.OnCT_TT_IdTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLVT_ThongTinTinh_SoGiaoThong_QLVT_CongTyVanTai", Storage="_QLVT_ThongTinTinh_SoGiaoThong", ThisKey="TS_IdTinh_So", OtherKey="TS_IdTinh_So", IsForeignKey=true)]
		public QLVT_ThongTinTinh_SoGiaoThong QLVT_ThongTinTinh_SoGiaoThong
		{
			get
			{
				return this._QLVT_ThongTinTinh_SoGiaoThong.Entity;
			}
			set
			{
				QLVT_ThongTinTinh_SoGiaoThong previousValue = this._QLVT_ThongTinTinh_SoGiaoThong.Entity;
				if (((previousValue != value) 
							|| (this._QLVT_ThongTinTinh_SoGiaoThong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QLVT_ThongTinTinh_SoGiaoThong.Entity = null;
						previousValue.QLVT_CongTyVanTais.Remove(this);
					}
					this._QLVT_ThongTinTinh_SoGiaoThong.Entity = value;
					if ((value != null))
					{
						value.QLVT_CongTyVanTais.Add(this);
						this._TS_IdTinh_So = value.TS_IdTinh_So;
					}
					else
					{
						this._TS_IdTinh_So = default(Nullable<int>);
					}
					this.SendPropertyChanged("QLVT_ThongTinTinh_SoGiaoThong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
