#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TramTiepNhan.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVanTai_2017")]
	public partial class HeThongDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHT_NhatKy(HT_NhatKy instance);
    partial void UpdateHT_NhatKy(HT_NhatKy instance);
    partial void DeleteHT_NhatKy(HT_NhatKy instance);
    partial void InsertNhatTrinhXe(NhatTrinhXe instance);
    partial void UpdateNhatTrinhXe(NhatTrinhXe instance);
    partial void DeleteNhatTrinhXe(NhatTrinhXe instance);
    partial void InsertHT_PhanQuyen(HT_PhanQuyen instance);
    partial void UpdateHT_PhanQuyen(HT_PhanQuyen instance);
    partial void DeleteHT_PhanQuyen(HT_PhanQuyen instance);
    partial void InsertHT_Quyen(HT_Quyen instance);
    partial void UpdateHT_Quyen(HT_Quyen instance);
    partial void DeleteHT_Quyen(HT_Quyen instance);
    partial void InsertHT_TaiKhoan(HT_TaiKhoan instance);
    partial void UpdateHT_TaiKhoan(HT_TaiKhoan instance);
    partial void DeleteHT_TaiKhoan(HT_TaiKhoan instance);
    partial void InsertHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void UpdateHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void DeleteHT_ThongTinTaiKhoan(HT_ThongTinTaiKhoan instance);
    partial void InsertTransfer_NhatKyTruyenTaiDuLieu(Transfer_NhatKyTruyenTaiDuLieu instance);
    partial void UpdateTransfer_NhatKyTruyenTaiDuLieu(Transfer_NhatKyTruyenTaiDuLieu instance);
    partial void DeleteTransfer_NhatKyTruyenTaiDuLieu(Transfer_NhatKyTruyenTaiDuLieu instance);
    partial void InsertTransfer_UngDungTruyenTaiDuLieu(Transfer_UngDungTruyenTaiDuLieu instance);
    partial void UpdateTransfer_UngDungTruyenTaiDuLieu(Transfer_UngDungTruyenTaiDuLieu instance);
    partial void DeleteTransfer_UngDungTruyenTaiDuLieu(Transfer_UngDungTruyenTaiDuLieu instance);
    partial void InsertQLVT_ThongTinXe(QLVT_ThongTinXe instance);
    partial void UpdateQLVT_ThongTinXe(QLVT_ThongTinXe instance);
    partial void DeleteQLVT_ThongTinXe(QLVT_ThongTinXe instance);
    partial void InsertQLVT_LuongTuyen(QLVT_LuongTuyen instance);
    partial void UpdateQLVT_LuongTuyen(QLVT_LuongTuyen instance);
    partial void DeleteQLVT_LuongTuyen(QLVT_LuongTuyen instance);
    partial void InsertQLVT_CongTyVanTai(QLVT_CongTyVanTai instance);
    partial void UpdateQLVT_CongTyVanTai(QLVT_CongTyVanTai instance);
    partial void DeleteQLVT_CongTyVanTai(QLVT_CongTyVanTai instance);
    partial void InsertQLVT_ThongTinBenXe(QLVT_ThongTinBenXe instance);
    partial void UpdateQLVT_ThongTinBenXe(QLVT_ThongTinBenXe instance);
    partial void DeleteQLVT_ThongTinBenXe(QLVT_ThongTinBenXe instance);
    #endregion
		
		public HeThongDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLVanTai_2017ConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HeThongDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HeThongDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HeThongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HeThongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HT_NhatKy> HT_NhatKies
		{
			get
			{
				return this.GetTable<HT_NhatKy>();
			}
		}
		
		public System.Data.Linq.Table<NhatTrinhXe> NhatTrinhXes
		{
			get
			{
				return this.GetTable<NhatTrinhXe>();
			}
		}
		
		public System.Data.Linq.Table<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this.GetTable<HT_PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<HT_Quyen> HT_Quyens
		{
			get
			{
				return this.GetTable<HT_Quyen>();
			}
		}
		
		public System.Data.Linq.Table<HT_TaiKhoan> HT_TaiKhoans
		{
			get
			{
				return this.GetTable<HT_TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<HT_ThongTinTaiKhoan> HT_ThongTinTaiKhoans
		{
			get
			{
				return this.GetTable<HT_ThongTinTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<Transfer_NhatKyTruyenTaiDuLieu> Transfer_NhatKyTruyenTaiDuLieus
		{
			get
			{
				return this.GetTable<Transfer_NhatKyTruyenTaiDuLieu>();
			}
		}
		
		public System.Data.Linq.Table<Transfer_UngDungTruyenTaiDuLieu> Transfer_UngDungTruyenTaiDuLieus
		{
			get
			{
				return this.GetTable<Transfer_UngDungTruyenTaiDuLieu>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_ThongTinXe> QLVT_ThongTinXes
		{
			get
			{
				return this.GetTable<QLVT_ThongTinXe>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_LuongTuyen> QLVT_LuongTuyens
		{
			get
			{
				return this.GetTable<QLVT_LuongTuyen>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_CongTyVanTai> QLVT_CongTyVanTais
		{
			get
			{
				return this.GetTable<QLVT_CongTyVanTai>();
			}
		}
		
		public System.Data.Linq.Table<QLVT_ThongTinBenXe> QLVT_ThongTinBenXes
		{
			get
			{
				return this.GetTable<QLVT_ThongTinBenXe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_NhatKy")]
	public partial class HT_NhatKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDNhatKy;
		
		private string _TenNhatKy;
		
		private string _LoaiNhatKy;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _ThoiGianTao;
		
		private System.Nullable<long> _IDTaiKhoan;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNhatKyChanging(long value);
    partial void OnIDNhatKyChanged();
    partial void OnTenNhatKyChanging(string value);
    partial void OnTenNhatKyChanged();
    partial void OnLoaiNhatKyChanging(string value);
    partial void OnLoaiNhatKyChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnThoiGianTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTaoChanged();
    partial void OnIDTaiKhoanChanging(System.Nullable<long> value);
    partial void OnIDTaiKhoanChanged();
    #endregion
		
		public HT_NhatKy()
		{
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhatKy", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDNhatKy
		{
			get
			{
				return this._IDNhatKy;
			}
			set
			{
				if ((this._IDNhatKy != value))
				{
					this.OnIDNhatKyChanging(value);
					this.SendPropertyChanging();
					this._IDNhatKy = value;
					this.SendPropertyChanged("IDNhatKy");
					this.OnIDNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhatKy", DbType="NVarChar(MAX)")]
		public string TenNhatKy
		{
			get
			{
				return this._TenNhatKy;
			}
			set
			{
				if ((this._TenNhatKy != value))
				{
					this.OnTenNhatKyChanging(value);
					this.SendPropertyChanging();
					this._TenNhatKy = value;
					this.SendPropertyChanged("TenNhatKy");
					this.OnTenNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNhatKy", DbType="NVarChar(MAX)")]
		public string LoaiNhatKy
		{
			get
			{
				return this._LoaiNhatKy;
			}
			set
			{
				if ((this._LoaiNhatKy != value))
				{
					this.OnLoaiNhatKyChanging(value);
					this.SendPropertyChanging();
					this._LoaiNhatKy = value;
					this.SendPropertyChanged("LoaiNhatKy");
					this.OnLoaiNhatKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt")]
		public System.Nullable<long> IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_NhatKy", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_NhatKies.Remove(this);
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_NhatKies.Add(this);
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(Nullable<long>);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhatTrinhXe")]
	public partial class NhatTrinhXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _TX_IdXe;
		
		private System.Nullable<long> _LT_IdLuongTuyen;
		
		private System.Nullable<int> _CT_IdCongTyVT;
		
		private System.Nullable<int> _IdBenDi;
		
		private string _BienSoDi;
		
		private System.Nullable<System.DateTime> _GioVaoBen;
		
		private System.Nullable<System.DateTime> _GioXuatBenKeHoach;
		
		private System.Nullable<System.DateTime> _GioCapXuatBen;
		
		private System.Nullable<System.DateTime> _GioRaBen;
		
		private System.Nullable<int> _SoKhach;
		
		private System.Nullable<bool> _XeXepKhach;
		
		private System.Nullable<bool> _XeKhongDuDieuKien;
		
		private System.Nullable<bool> _XeVeDonVi;
		
		private System.Nullable<bool> _XeTangCuong;
		
		private System.Nullable<int> _IdBenDen;
		
		private System.Nullable<System.DateTime> _GioDenBen;
		
		private string _GhiChu;
		
		private EntitySet<Transfer_NhatKyTruyenTaiDuLieu> _Transfer_NhatKyTruyenTaiDuLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnTX_IdXeChanging(System.Nullable<long> value);
    partial void OnTX_IdXeChanged();
    partial void OnLT_IdLuongTuyenChanging(System.Nullable<long> value);
    partial void OnLT_IdLuongTuyenChanged();
    partial void OnCT_IdCongTyVTChanging(System.Nullable<int> value);
    partial void OnCT_IdCongTyVTChanged();
    partial void OnIdBenDiChanging(System.Nullable<int> value);
    partial void OnIdBenDiChanged();
    partial void OnBienSoDiChanging(string value);
    partial void OnBienSoDiChanged();
    partial void OnGioVaoBenChanging(System.Nullable<System.DateTime> value);
    partial void OnGioVaoBenChanged();
    partial void OnGioXuatBenKeHoachChanging(System.Nullable<System.DateTime> value);
    partial void OnGioXuatBenKeHoachChanged();
    partial void OnGioCapXuatBenChanging(System.Nullable<System.DateTime> value);
    partial void OnGioCapXuatBenChanged();
    partial void OnGioRaBenChanging(System.Nullable<System.DateTime> value);
    partial void OnGioRaBenChanged();
    partial void OnSoKhachChanging(System.Nullable<int> value);
    partial void OnSoKhachChanged();
    partial void OnXeXepKhachChanging(System.Nullable<bool> value);
    partial void OnXeXepKhachChanged();
    partial void OnXeKhongDuDieuKienChanging(System.Nullable<bool> value);
    partial void OnXeKhongDuDieuKienChanged();
    partial void OnXeVeDonViChanging(System.Nullable<bool> value);
    partial void OnXeVeDonViChanged();
    partial void OnXeTangCuongChanging(System.Nullable<bool> value);
    partial void OnXeTangCuongChanged();
    partial void OnIdBenDenChanging(System.Nullable<int> value);
    partial void OnIdBenDenChanged();
    partial void OnGioDenBenChanging(System.Nullable<System.DateTime> value);
    partial void OnGioDenBenChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NhatTrinhXe()
		{
			this._Transfer_NhatKyTruyenTaiDuLieus = new EntitySet<Transfer_NhatKyTruyenTaiDuLieu>(new Action<Transfer_NhatKyTruyenTaiDuLieu>(this.attach_Transfer_NhatKyTruyenTaiDuLieus), new Action<Transfer_NhatKyTruyenTaiDuLieu>(this.detach_Transfer_NhatKyTruyenTaiDuLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TX_IdXe", DbType="BigInt")]
		public System.Nullable<long> TX_IdXe
		{
			get
			{
				return this._TX_IdXe;
			}
			set
			{
				if ((this._TX_IdXe != value))
				{
					this.OnTX_IdXeChanging(value);
					this.SendPropertyChanging();
					this._TX_IdXe = value;
					this.SendPropertyChanged("TX_IdXe");
					this.OnTX_IdXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_IdLuongTuyen", DbType="BigInt")]
		public System.Nullable<long> LT_IdLuongTuyen
		{
			get
			{
				return this._LT_IdLuongTuyen;
			}
			set
			{
				if ((this._LT_IdLuongTuyen != value))
				{
					this.OnLT_IdLuongTuyenChanging(value);
					this.SendPropertyChanging();
					this._LT_IdLuongTuyen = value;
					this.SendPropertyChanged("LT_IdLuongTuyen");
					this.OnLT_IdLuongTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_IdCongTyVT", DbType="Int")]
		public System.Nullable<int> CT_IdCongTyVT
		{
			get
			{
				return this._CT_IdCongTyVT;
			}
			set
			{
				if ((this._CT_IdCongTyVT != value))
				{
					this.OnCT_IdCongTyVTChanging(value);
					this.SendPropertyChanging();
					this._CT_IdCongTyVT = value;
					this.SendPropertyChanged("CT_IdCongTyVT");
					this.OnCT_IdCongTyVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBenDi", DbType="Int")]
		public System.Nullable<int> IdBenDi
		{
			get
			{
				return this._IdBenDi;
			}
			set
			{
				if ((this._IdBenDi != value))
				{
					this.OnIdBenDiChanging(value);
					this.SendPropertyChanging();
					this._IdBenDi = value;
					this.SendPropertyChanged("IdBenDi");
					this.OnIdBenDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSoDi", DbType="VarChar(16)")]
		public string BienSoDi
		{
			get
			{
				return this._BienSoDi;
			}
			set
			{
				if ((this._BienSoDi != value))
				{
					this.OnBienSoDiChanging(value);
					this.SendPropertyChanging();
					this._BienSoDi = value;
					this.SendPropertyChanged("BienSoDi");
					this.OnBienSoDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioVaoBen", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioVaoBen
		{
			get
			{
				return this._GioVaoBen;
			}
			set
			{
				if ((this._GioVaoBen != value))
				{
					this.OnGioVaoBenChanging(value);
					this.SendPropertyChanging();
					this._GioVaoBen = value;
					this.SendPropertyChanged("GioVaoBen");
					this.OnGioVaoBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioXuatBenKeHoach", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioXuatBenKeHoach
		{
			get
			{
				return this._GioXuatBenKeHoach;
			}
			set
			{
				if ((this._GioXuatBenKeHoach != value))
				{
					this.OnGioXuatBenKeHoachChanging(value);
					this.SendPropertyChanging();
					this._GioXuatBenKeHoach = value;
					this.SendPropertyChanged("GioXuatBenKeHoach");
					this.OnGioXuatBenKeHoachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioCapXuatBen", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioCapXuatBen
		{
			get
			{
				return this._GioCapXuatBen;
			}
			set
			{
				if ((this._GioCapXuatBen != value))
				{
					this.OnGioCapXuatBenChanging(value);
					this.SendPropertyChanging();
					this._GioCapXuatBen = value;
					this.SendPropertyChanged("GioCapXuatBen");
					this.OnGioCapXuatBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioRaBen", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioRaBen
		{
			get
			{
				return this._GioRaBen;
			}
			set
			{
				if ((this._GioRaBen != value))
				{
					this.OnGioRaBenChanging(value);
					this.SendPropertyChanging();
					this._GioRaBen = value;
					this.SendPropertyChanged("GioRaBen");
					this.OnGioRaBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoKhach", DbType="Int")]
		public System.Nullable<int> SoKhach
		{
			get
			{
				return this._SoKhach;
			}
			set
			{
				if ((this._SoKhach != value))
				{
					this.OnSoKhachChanging(value);
					this.SendPropertyChanging();
					this._SoKhach = value;
					this.SendPropertyChanged("SoKhach");
					this.OnSoKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XeXepKhach", DbType="Bit")]
		public System.Nullable<bool> XeXepKhach
		{
			get
			{
				return this._XeXepKhach;
			}
			set
			{
				if ((this._XeXepKhach != value))
				{
					this.OnXeXepKhachChanging(value);
					this.SendPropertyChanging();
					this._XeXepKhach = value;
					this.SendPropertyChanged("XeXepKhach");
					this.OnXeXepKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XeKhongDuDieuKien", DbType="Bit")]
		public System.Nullable<bool> XeKhongDuDieuKien
		{
			get
			{
				return this._XeKhongDuDieuKien;
			}
			set
			{
				if ((this._XeKhongDuDieuKien != value))
				{
					this.OnXeKhongDuDieuKienChanging(value);
					this.SendPropertyChanging();
					this._XeKhongDuDieuKien = value;
					this.SendPropertyChanged("XeKhongDuDieuKien");
					this.OnXeKhongDuDieuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XeVeDonVi", DbType="Bit")]
		public System.Nullable<bool> XeVeDonVi
		{
			get
			{
				return this._XeVeDonVi;
			}
			set
			{
				if ((this._XeVeDonVi != value))
				{
					this.OnXeVeDonViChanging(value);
					this.SendPropertyChanging();
					this._XeVeDonVi = value;
					this.SendPropertyChanged("XeVeDonVi");
					this.OnXeVeDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XeTangCuong", DbType="Bit")]
		public System.Nullable<bool> XeTangCuong
		{
			get
			{
				return this._XeTangCuong;
			}
			set
			{
				if ((this._XeTangCuong != value))
				{
					this.OnXeTangCuongChanging(value);
					this.SendPropertyChanging();
					this._XeTangCuong = value;
					this.SendPropertyChanged("XeTangCuong");
					this.OnXeTangCuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBenDen", DbType="Int")]
		public System.Nullable<int> IdBenDen
		{
			get
			{
				return this._IdBenDen;
			}
			set
			{
				if ((this._IdBenDen != value))
				{
					this.OnIdBenDenChanging(value);
					this.SendPropertyChanging();
					this._IdBenDen = value;
					this.SendPropertyChanged("IdBenDen");
					this.OnIdBenDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioDenBen", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioDenBen
		{
			get
			{
				return this._GioDenBen;
			}
			set
			{
				if ((this._GioDenBen != value))
				{
					this.OnGioDenBenChanging(value);
					this.SendPropertyChanging();
					this._GioDenBen = value;
					this.SendPropertyChanged("GioDenBen");
					this.OnGioDenBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhatTrinhXe_Transfer_NhatKyTruyenTaiDuLieu", Storage="_Transfer_NhatKyTruyenTaiDuLieus", ThisKey="Id", OtherKey="IDNhatTrinhXe")]
		public EntitySet<Transfer_NhatKyTruyenTaiDuLieu> Transfer_NhatKyTruyenTaiDuLieus
		{
			get
			{
				return this._Transfer_NhatKyTruyenTaiDuLieus;
			}
			set
			{
				this._Transfer_NhatKyTruyenTaiDuLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transfer_NhatKyTruyenTaiDuLieus(Transfer_NhatKyTruyenTaiDuLieu entity)
		{
			this.SendPropertyChanging();
			entity.NhatTrinhXe = this;
		}
		
		private void detach_Transfer_NhatKyTruyenTaiDuLieus(Transfer_NhatKyTruyenTaiDuLieu entity)
		{
			this.SendPropertyChanging();
			entity.NhatTrinhXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_PhanQuyen")]
	public partial class HT_PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private long _IDQuyen;
		
		private EntityRef<HT_Quyen> _HT_Quyen;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnIDQuyenChanging(long value);
    partial void OnIDQuyenChanged();
    #endregion
		
		public HT_PhanQuyen()
		{
			this._HT_Quyen = default(EntityRef<HT_Quyen>);
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					if (this._HT_Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_Quyen_HT_PhanQuyen", Storage="_HT_Quyen", ThisKey="IDQuyen", OtherKey="IDQuyen", IsForeignKey=true)]
		public HT_Quyen HT_Quyen
		{
			get
			{
				return this._HT_Quyen.Entity;
			}
			set
			{
				HT_Quyen previousValue = this._HT_Quyen.Entity;
				if (((previousValue != value) 
							|| (this._HT_Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_Quyen.Entity = null;
						previousValue.HT_PhanQuyens.Remove(this);
					}
					this._HT_Quyen.Entity = value;
					if ((value != null))
					{
						value.HT_PhanQuyens.Add(this);
						this._IDQuyen = value.IDQuyen;
					}
					else
					{
						this._IDQuyen = default(long);
					}
					this.SendPropertyChanged("HT_Quyen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_PhanQuyen", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_PhanQuyens.Remove(this);
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_PhanQuyens.Add(this);
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(long);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_Quyen")]
	public partial class HT_Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDQuyen;
		
		private string _TenQuyen;
		
		private string _NhomQuyen;
		
		private EntitySet<HT_PhanQuyen> _HT_PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDQuyenChanging(long value);
    partial void OnIDQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    partial void OnNhomQuyenChanging(string value);
    partial void OnNhomQuyenChanged();
    #endregion
		
		public HT_Quyen()
		{
			this._HT_PhanQuyens = new EntitySet<HT_PhanQuyen>(new Action<HT_PhanQuyen>(this.attach_HT_PhanQuyens), new Action<HT_PhanQuyen>(this.detach_HT_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomQuyen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NhomQuyen
		{
			get
			{
				return this._NhomQuyen;
			}
			set
			{
				if ((this._NhomQuyen != value))
				{
					this.OnNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._NhomQuyen = value;
					this.SendPropertyChanged("NhomQuyen");
					this.OnNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_Quyen_HT_PhanQuyen", Storage="_HT_PhanQuyens", ThisKey="IDQuyen", OtherKey="IDQuyen")]
		public EntitySet<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this._HT_PhanQuyens;
			}
			set
			{
				this._HT_PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_Quyen = this;
		}
		
		private void detach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_Quyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_TaiKhoan")]
	public partial class HT_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private System.DateTime _ThoiGianTao;
		
		private System.Nullable<long> _IDBen;
		
		private System.Nullable<long> _IDDonViVanTai;
		
		private System.Nullable<long> _IDSo;
		
		private EntitySet<HT_NhatKy> _HT_NhatKies;
		
		private EntitySet<HT_PhanQuyen> _HT_PhanQuyens;
		
		private EntityRef<HT_ThongTinTaiKhoan> _HT_ThongTinTaiKhoan;
		
		private EntitySet<Transfer_UngDungTruyenTaiDuLieu> _Transfer_UngDungTruyenTaiDuLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnThoiGianTaoChanging(System.DateTime value);
    partial void OnThoiGianTaoChanged();
    partial void OnIDBenChanging(System.Nullable<long> value);
    partial void OnIDBenChanged();
    partial void OnIDDonViVanTaiChanging(System.Nullable<long> value);
    partial void OnIDDonViVanTaiChanged();
    partial void OnIDSoChanging(System.Nullable<long> value);
    partial void OnIDSoChanged();
    #endregion
		
		public HT_TaiKhoan()
		{
			this._HT_NhatKies = new EntitySet<HT_NhatKy>(new Action<HT_NhatKy>(this.attach_HT_NhatKies), new Action<HT_NhatKy>(this.detach_HT_NhatKies));
			this._HT_PhanQuyens = new EntitySet<HT_PhanQuyen>(new Action<HT_PhanQuyen>(this.attach_HT_PhanQuyens), new Action<HT_PhanQuyen>(this.detach_HT_PhanQuyens));
			this._HT_ThongTinTaiKhoan = default(EntityRef<HT_ThongTinTaiKhoan>);
			this._Transfer_UngDungTruyenTaiDuLieus = new EntitySet<Transfer_UngDungTruyenTaiDuLieu>(new Action<Transfer_UngDungTruyenTaiDuLieu>(this.attach_Transfer_UngDungTruyenTaiDuLieus), new Action<Transfer_UngDungTruyenTaiDuLieu>(this.detach_Transfer_UngDungTruyenTaiDuLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBen", DbType="BigInt")]
		public System.Nullable<long> IDBen
		{
			get
			{
				return this._IDBen;
			}
			set
			{
				if ((this._IDBen != value))
				{
					this.OnIDBenChanging(value);
					this.SendPropertyChanging();
					this._IDBen = value;
					this.SendPropertyChanged("IDBen");
					this.OnIDBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDonViVanTai", DbType="BigInt")]
		public System.Nullable<long> IDDonViVanTai
		{
			get
			{
				return this._IDDonViVanTai;
			}
			set
			{
				if ((this._IDDonViVanTai != value))
				{
					this.OnIDDonViVanTaiChanging(value);
					this.SendPropertyChanging();
					this._IDDonViVanTai = value;
					this.SendPropertyChanged("IDDonViVanTai");
					this.OnIDDonViVanTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSo", DbType="BigInt")]
		public System.Nullable<long> IDSo
		{
			get
			{
				return this._IDSo;
			}
			set
			{
				if ((this._IDSo != value))
				{
					this.OnIDSoChanging(value);
					this.SendPropertyChanging();
					this._IDSo = value;
					this.SendPropertyChanged("IDSo");
					this.OnIDSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_NhatKy", Storage="_HT_NhatKies", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan")]
		public EntitySet<HT_NhatKy> HT_NhatKies
		{
			get
			{
				return this._HT_NhatKies;
			}
			set
			{
				this._HT_NhatKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_PhanQuyen", Storage="_HT_PhanQuyens", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan")]
		public EntitySet<HT_PhanQuyen> HT_PhanQuyens
		{
			get
			{
				return this._HT_PhanQuyens;
			}
			set
			{
				this._HT_PhanQuyens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_ThongTinTaiKhoan", Storage="_HT_ThongTinTaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsUnique=true, IsForeignKey=false)]
		public HT_ThongTinTaiKhoan HT_ThongTinTaiKhoan
		{
			get
			{
				return this._HT_ThongTinTaiKhoan.Entity;
			}
			set
			{
				HT_ThongTinTaiKhoan previousValue = this._HT_ThongTinTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_ThongTinTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_ThongTinTaiKhoan.Entity = null;
						previousValue.HT_TaiKhoan = null;
					}
					this._HT_ThongTinTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_TaiKhoan = this;
					}
					this.SendPropertyChanged("HT_ThongTinTaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_Transfer_UngDungTruyenTaiDuLieu", Storage="_Transfer_UngDungTruyenTaiDuLieus", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan")]
		public EntitySet<Transfer_UngDungTruyenTaiDuLieu> Transfer_UngDungTruyenTaiDuLieus
		{
			get
			{
				return this._Transfer_UngDungTruyenTaiDuLieus;
			}
			set
			{
				this._Transfer_UngDungTruyenTaiDuLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HT_NhatKies(HT_NhatKy entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = this;
		}
		
		private void detach_HT_NhatKies(HT_NhatKy entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = null;
		}
		
		private void attach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = this;
		}
		
		private void detach_HT_PhanQuyens(HT_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = null;
		}
		
		private void attach_Transfer_UngDungTruyenTaiDuLieus(Transfer_UngDungTruyenTaiDuLieu entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = this;
		}
		
		private void detach_Transfer_UngDungTruyenTaiDuLieus(Transfer_UngDungTruyenTaiDuLieu entity)
		{
			this.SendPropertyChanging();
			entity.HT_TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_ThongTinTaiKhoan")]
	public partial class HT_ThongTinTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTaiKhoan;
		
		private string _GhiChu;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public HT_ThongTinTaiKhoan()
		{
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_HT_ThongTinTaiKhoan", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.HT_ThongTinTaiKhoan = null;
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HT_ThongTinTaiKhoan = this;
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(long);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transfer_NhatKyTruyenTaiDuLieu")]
	public partial class Transfer_NhatKyTruyenTaiDuLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDNhatKyTruyenTaiDuLieu;
		
		private long _IDUngDungTruyenTaiDuLieu;
		
		private string _DuLieu;
		
		private string _ThongTinThem;
		
		private System.Nullable<long> _IDNhatTrinhXe;
		
		private EntityRef<NhatTrinhXe> _NhatTrinhXe;
		
		private EntityRef<Transfer_UngDungTruyenTaiDuLieu> _Transfer_UngDungTruyenTaiDuLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNhatKyTruyenTaiDuLieuChanging(long value);
    partial void OnIDNhatKyTruyenTaiDuLieuChanged();
    partial void OnIDUngDungTruyenTaiDuLieuChanging(long value);
    partial void OnIDUngDungTruyenTaiDuLieuChanged();
    partial void OnDuLieuChanging(string value);
    partial void OnDuLieuChanged();
    partial void OnThongTinThemChanging(string value);
    partial void OnThongTinThemChanged();
    partial void OnIDNhatTrinhXeChanging(System.Nullable<long> value);
    partial void OnIDNhatTrinhXeChanged();
    #endregion
		
		public Transfer_NhatKyTruyenTaiDuLieu()
		{
			this._NhatTrinhXe = default(EntityRef<NhatTrinhXe>);
			this._Transfer_UngDungTruyenTaiDuLieu = default(EntityRef<Transfer_UngDungTruyenTaiDuLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhatKyTruyenTaiDuLieu", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDNhatKyTruyenTaiDuLieu
		{
			get
			{
				return this._IDNhatKyTruyenTaiDuLieu;
			}
			set
			{
				if ((this._IDNhatKyTruyenTaiDuLieu != value))
				{
					this.OnIDNhatKyTruyenTaiDuLieuChanging(value);
					this.SendPropertyChanging();
					this._IDNhatKyTruyenTaiDuLieu = value;
					this.SendPropertyChanged("IDNhatKyTruyenTaiDuLieu");
					this.OnIDNhatKyTruyenTaiDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUngDungTruyenTaiDuLieu", DbType="BigInt NOT NULL")]
		public long IDUngDungTruyenTaiDuLieu
		{
			get
			{
				return this._IDUngDungTruyenTaiDuLieu;
			}
			set
			{
				if ((this._IDUngDungTruyenTaiDuLieu != value))
				{
					if (this._Transfer_UngDungTruyenTaiDuLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDUngDungTruyenTaiDuLieuChanging(value);
					this.SendPropertyChanging();
					this._IDUngDungTruyenTaiDuLieu = value;
					this.SendPropertyChanged("IDUngDungTruyenTaiDuLieu");
					this.OnIDUngDungTruyenTaiDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuLieu", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DuLieu
		{
			get
			{
				return this._DuLieu;
			}
			set
			{
				if ((this._DuLieu != value))
				{
					this.OnDuLieuChanging(value);
					this.SendPropertyChanging();
					this._DuLieu = value;
					this.SendPropertyChanged("DuLieu");
					this.OnDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinThem", DbType="NVarChar(MAX)")]
		public string ThongTinThem
		{
			get
			{
				return this._ThongTinThem;
			}
			set
			{
				if ((this._ThongTinThem != value))
				{
					this.OnThongTinThemChanging(value);
					this.SendPropertyChanging();
					this._ThongTinThem = value;
					this.SendPropertyChanged("ThongTinThem");
					this.OnThongTinThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhatTrinhXe", DbType="BigInt")]
		public System.Nullable<long> IDNhatTrinhXe
		{
			get
			{
				return this._IDNhatTrinhXe;
			}
			set
			{
				if ((this._IDNhatTrinhXe != value))
				{
					if (this._NhatTrinhXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNhatTrinhXeChanging(value);
					this.SendPropertyChanging();
					this._IDNhatTrinhXe = value;
					this.SendPropertyChanged("IDNhatTrinhXe");
					this.OnIDNhatTrinhXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhatTrinhXe_Transfer_NhatKyTruyenTaiDuLieu", Storage="_NhatTrinhXe", ThisKey="IDNhatTrinhXe", OtherKey="Id", IsForeignKey=true)]
		public NhatTrinhXe NhatTrinhXe
		{
			get
			{
				return this._NhatTrinhXe.Entity;
			}
			set
			{
				NhatTrinhXe previousValue = this._NhatTrinhXe.Entity;
				if (((previousValue != value) 
							|| (this._NhatTrinhXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhatTrinhXe.Entity = null;
						previousValue.Transfer_NhatKyTruyenTaiDuLieus.Remove(this);
					}
					this._NhatTrinhXe.Entity = value;
					if ((value != null))
					{
						value.Transfer_NhatKyTruyenTaiDuLieus.Add(this);
						this._IDNhatTrinhXe = value.Id;
					}
					else
					{
						this._IDNhatTrinhXe = default(Nullable<long>);
					}
					this.SendPropertyChanged("NhatTrinhXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transfer_UngDungTruyenTaiDuLieu_Transfer_NhatKyTruyenTaiDuLieu", Storage="_Transfer_UngDungTruyenTaiDuLieu", ThisKey="IDUngDungTruyenTaiDuLieu", OtherKey="IDUngDungTruyenTaiDuLieu", IsForeignKey=true)]
		public Transfer_UngDungTruyenTaiDuLieu Transfer_UngDungTruyenTaiDuLieu
		{
			get
			{
				return this._Transfer_UngDungTruyenTaiDuLieu.Entity;
			}
			set
			{
				Transfer_UngDungTruyenTaiDuLieu previousValue = this._Transfer_UngDungTruyenTaiDuLieu.Entity;
				if (((previousValue != value) 
							|| (this._Transfer_UngDungTruyenTaiDuLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transfer_UngDungTruyenTaiDuLieu.Entity = null;
						previousValue.Transfer_NhatKyTruyenTaiDuLieus.Remove(this);
					}
					this._Transfer_UngDungTruyenTaiDuLieu.Entity = value;
					if ((value != null))
					{
						value.Transfer_NhatKyTruyenTaiDuLieus.Add(this);
						this._IDUngDungTruyenTaiDuLieu = value.IDUngDungTruyenTaiDuLieu;
					}
					else
					{
						this._IDUngDungTruyenTaiDuLieu = default(long);
					}
					this.SendPropertyChanged("Transfer_UngDungTruyenTaiDuLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transfer_UngDungTruyenTaiDuLieu")]
	public partial class Transfer_UngDungTruyenTaiDuLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDUngDungTruyenTaiDuLieu;
		
		private long _IDTaiKhoan;
		
		private string _MaUngDung;
		
		private string _MaBiMat;
		
		private System.DateTime _ThoiGianTao;
		
		private EntitySet<Transfer_NhatKyTruyenTaiDuLieu> _Transfer_NhatKyTruyenTaiDuLieus;
		
		private EntityRef<HT_TaiKhoan> _HT_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUngDungTruyenTaiDuLieuChanging(long value);
    partial void OnIDUngDungTruyenTaiDuLieuChanged();
    partial void OnIDTaiKhoanChanging(long value);
    partial void OnIDTaiKhoanChanged();
    partial void OnMaUngDungChanging(string value);
    partial void OnMaUngDungChanged();
    partial void OnMaBiMatChanging(string value);
    partial void OnMaBiMatChanged();
    partial void OnThoiGianTaoChanging(System.DateTime value);
    partial void OnThoiGianTaoChanged();
    #endregion
		
		public Transfer_UngDungTruyenTaiDuLieu()
		{
			this._Transfer_NhatKyTruyenTaiDuLieus = new EntitySet<Transfer_NhatKyTruyenTaiDuLieu>(new Action<Transfer_NhatKyTruyenTaiDuLieu>(this.attach_Transfer_NhatKyTruyenTaiDuLieus), new Action<Transfer_NhatKyTruyenTaiDuLieu>(this.detach_Transfer_NhatKyTruyenTaiDuLieus));
			this._HT_TaiKhoan = default(EntityRef<HT_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUngDungTruyenTaiDuLieu", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDUngDungTruyenTaiDuLieu
		{
			get
			{
				return this._IDUngDungTruyenTaiDuLieu;
			}
			set
			{
				if ((this._IDUngDungTruyenTaiDuLieu != value))
				{
					this.OnIDUngDungTruyenTaiDuLieuChanging(value);
					this.SendPropertyChanging();
					this._IDUngDungTruyenTaiDuLieu = value;
					this.SendPropertyChanged("IDUngDungTruyenTaiDuLieu");
					this.OnIDUngDungTruyenTaiDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="BigInt NOT NULL")]
		public long IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._HT_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUngDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MaUngDung
		{
			get
			{
				return this._MaUngDung;
			}
			set
			{
				if ((this._MaUngDung != value))
				{
					this.OnMaUngDungChanging(value);
					this.SendPropertyChanging();
					this._MaUngDung = value;
					this.SendPropertyChanged("MaUngDung");
					this.OnMaUngDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBiMat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MaBiMat
		{
			get
			{
				return this._MaBiMat;
			}
			set
			{
				if ((this._MaBiMat != value))
				{
					this.OnMaBiMatChanging(value);
					this.SendPropertyChanging();
					this._MaBiMat = value;
					this.SendPropertyChanged("MaBiMat");
					this.OnMaBiMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transfer_UngDungTruyenTaiDuLieu_Transfer_NhatKyTruyenTaiDuLieu", Storage="_Transfer_NhatKyTruyenTaiDuLieus", ThisKey="IDUngDungTruyenTaiDuLieu", OtherKey="IDUngDungTruyenTaiDuLieu")]
		public EntitySet<Transfer_NhatKyTruyenTaiDuLieu> Transfer_NhatKyTruyenTaiDuLieus
		{
			get
			{
				return this._Transfer_NhatKyTruyenTaiDuLieus;
			}
			set
			{
				this._Transfer_NhatKyTruyenTaiDuLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_TaiKhoan_Transfer_UngDungTruyenTaiDuLieu", Storage="_HT_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public HT_TaiKhoan HT_TaiKhoan
		{
			get
			{
				return this._HT_TaiKhoan.Entity;
			}
			set
			{
				HT_TaiKhoan previousValue = this._HT_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._HT_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_TaiKhoan.Entity = null;
						previousValue.Transfer_UngDungTruyenTaiDuLieus.Remove(this);
					}
					this._HT_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.Transfer_UngDungTruyenTaiDuLieus.Add(this);
						this._IDTaiKhoan = value.IDTaiKhoan;
					}
					else
					{
						this._IDTaiKhoan = default(long);
					}
					this.SendPropertyChanged("HT_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transfer_NhatKyTruyenTaiDuLieus(Transfer_NhatKyTruyenTaiDuLieu entity)
		{
			this.SendPropertyChanging();
			entity.Transfer_UngDungTruyenTaiDuLieu = this;
		}
		
		private void detach_Transfer_NhatKyTruyenTaiDuLieus(Transfer_NhatKyTruyenTaiDuLieu entity)
		{
			this.SendPropertyChanging();
			entity.Transfer_UngDungTruyenTaiDuLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_ThongTinXe")]
	public partial class QLVT_ThongTinXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _TX_IdXe;
		
		private string _TX_BienSoXe;
		
		private System.Nullable<int> _TX_MaSoXe;
		
		private int _TS_IdTinh_So;
		
		private System.Nullable<int> _CT_IdCongTyVT;
		
		private System.Nullable<int> _TX_TT_IdTrangThaiXe;
		
		private long _LT_IdLuongTuyen;
		
		private EntityRef<QLVT_CongTyVanTai> _QLVT_CongTyVanTai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTX_IdXeChanging(long value);
    partial void OnTX_IdXeChanged();
    partial void OnTX_BienSoXeChanging(string value);
    partial void OnTX_BienSoXeChanged();
    partial void OnTX_MaSoXeChanging(System.Nullable<int> value);
    partial void OnTX_MaSoXeChanged();
    partial void OnTS_IdTinh_SoChanging(int value);
    partial void OnTS_IdTinh_SoChanged();
    partial void OnCT_IdCongTyVTChanging(System.Nullable<int> value);
    partial void OnCT_IdCongTyVTChanged();
    partial void OnTX_TT_IdTrangThaiXeChanging(System.Nullable<int> value);
    partial void OnTX_TT_IdTrangThaiXeChanged();
    partial void OnLT_IdLuongTuyenChanging(long value);
    partial void OnLT_IdLuongTuyenChanged();
    #endregion
		
		public QLVT_ThongTinXe()
		{
			this._QLVT_CongTyVanTai = default(EntityRef<QLVT_CongTyVanTai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TX_IdXe", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long TX_IdXe
		{
			get
			{
				return this._TX_IdXe;
			}
			set
			{
				if ((this._TX_IdXe != value))
				{
					this.OnTX_IdXeChanging(value);
					this.SendPropertyChanging();
					this._TX_IdXe = value;
					this.SendPropertyChanged("TX_IdXe");
					this.OnTX_IdXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TX_BienSoXe", DbType="VarChar(16)")]
		public string TX_BienSoXe
		{
			get
			{
				return this._TX_BienSoXe;
			}
			set
			{
				if ((this._TX_BienSoXe != value))
				{
					this.OnTX_BienSoXeChanging(value);
					this.SendPropertyChanging();
					this._TX_BienSoXe = value;
					this.SendPropertyChanged("TX_BienSoXe");
					this.OnTX_BienSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TX_MaSoXe", DbType="Int")]
		public System.Nullable<int> TX_MaSoXe
		{
			get
			{
				return this._TX_MaSoXe;
			}
			set
			{
				if ((this._TX_MaSoXe != value))
				{
					this.OnTX_MaSoXeChanging(value);
					this.SendPropertyChanging();
					this._TX_MaSoXe = value;
					this.SendPropertyChanged("TX_MaSoXe");
					this.OnTX_MaSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdTinh_So", DbType="Int NOT NULL")]
		public int TS_IdTinh_So
		{
			get
			{
				return this._TS_IdTinh_So;
			}
			set
			{
				if ((this._TS_IdTinh_So != value))
				{
					this.OnTS_IdTinh_SoChanging(value);
					this.SendPropertyChanging();
					this._TS_IdTinh_So = value;
					this.SendPropertyChanged("TS_IdTinh_So");
					this.OnTS_IdTinh_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_IdCongTyVT", DbType="Int")]
		public System.Nullable<int> CT_IdCongTyVT
		{
			get
			{
				return this._CT_IdCongTyVT;
			}
			set
			{
				if ((this._CT_IdCongTyVT != value))
				{
					if (this._QLVT_CongTyVanTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCT_IdCongTyVTChanging(value);
					this.SendPropertyChanging();
					this._CT_IdCongTyVT = value;
					this.SendPropertyChanged("CT_IdCongTyVT");
					this.OnCT_IdCongTyVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TX_TT_IdTrangThaiXe", DbType="Int")]
		public System.Nullable<int> TX_TT_IdTrangThaiXe
		{
			get
			{
				return this._TX_TT_IdTrangThaiXe;
			}
			set
			{
				if ((this._TX_TT_IdTrangThaiXe != value))
				{
					this.OnTX_TT_IdTrangThaiXeChanging(value);
					this.SendPropertyChanging();
					this._TX_TT_IdTrangThaiXe = value;
					this.SendPropertyChanged("TX_TT_IdTrangThaiXe");
					this.OnTX_TT_IdTrangThaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_IdLuongTuyen", DbType="BigInt NOT NULL")]
		public long LT_IdLuongTuyen
		{
			get
			{
				return this._LT_IdLuongTuyen;
			}
			set
			{
				if ((this._LT_IdLuongTuyen != value))
				{
					this.OnLT_IdLuongTuyenChanging(value);
					this.SendPropertyChanging();
					this._LT_IdLuongTuyen = value;
					this.SendPropertyChanged("LT_IdLuongTuyen");
					this.OnLT_IdLuongTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLVT_CongTyVanTai_QLVT_ThongTinXe", Storage="_QLVT_CongTyVanTai", ThisKey="CT_IdCongTyVT", OtherKey="CT_IdCongTyVT", IsForeignKey=true)]
		public QLVT_CongTyVanTai QLVT_CongTyVanTai
		{
			get
			{
				return this._QLVT_CongTyVanTai.Entity;
			}
			set
			{
				QLVT_CongTyVanTai previousValue = this._QLVT_CongTyVanTai.Entity;
				if (((previousValue != value) 
							|| (this._QLVT_CongTyVanTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QLVT_CongTyVanTai.Entity = null;
						previousValue.QLVT_ThongTinXes.Remove(this);
					}
					this._QLVT_CongTyVanTai.Entity = value;
					if ((value != null))
					{
						value.QLVT_ThongTinXes.Add(this);
						this._CT_IdCongTyVT = value.CT_IdCongTyVT;
					}
					else
					{
						this._CT_IdCongTyVT = default(Nullable<int>);
					}
					this.SendPropertyChanged("QLVT_CongTyVanTai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_LuongTuyen")]
	public partial class QLVT_LuongTuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _LT_IdLuongTuyen;
		
		private string _LT_MaTuyen;
		
		private string _LT_HanhTrinhChay;
		
		private System.Nullable<double> _LT_CuLy;
		
		private System.Nullable<int> _LT_LuuLuongQuyDinh;
		
		private System.Nullable<int> _TT_IdTrangThaiTuyen;
		
		private System.Nullable<int> _LT_PL_IdLuongTuyen;
		
		private System.Nullable<long> _LT_DC_IdLuongTuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLT_IdLuongTuyenChanging(long value);
    partial void OnLT_IdLuongTuyenChanged();
    partial void OnLT_MaTuyenChanging(string value);
    partial void OnLT_MaTuyenChanged();
    partial void OnLT_HanhTrinhChayChanging(string value);
    partial void OnLT_HanhTrinhChayChanged();
    partial void OnLT_CuLyChanging(System.Nullable<double> value);
    partial void OnLT_CuLyChanged();
    partial void OnLT_LuuLuongQuyDinhChanging(System.Nullable<int> value);
    partial void OnLT_LuuLuongQuyDinhChanged();
    partial void OnTT_IdTrangThaiTuyenChanging(System.Nullable<int> value);
    partial void OnTT_IdTrangThaiTuyenChanged();
    partial void OnLT_PL_IdLuongTuyenChanging(System.Nullable<int> value);
    partial void OnLT_PL_IdLuongTuyenChanged();
    partial void OnLT_DC_IdLuongTuyenChanging(System.Nullable<long> value);
    partial void OnLT_DC_IdLuongTuyenChanged();
    #endregion
		
		public QLVT_LuongTuyen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_IdLuongTuyen", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long LT_IdLuongTuyen
		{
			get
			{
				return this._LT_IdLuongTuyen;
			}
			set
			{
				if ((this._LT_IdLuongTuyen != value))
				{
					this.OnLT_IdLuongTuyenChanging(value);
					this.SendPropertyChanging();
					this._LT_IdLuongTuyen = value;
					this.SendPropertyChanged("LT_IdLuongTuyen");
					this.OnLT_IdLuongTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_MaTuyen", DbType="VarChar(16)")]
		public string LT_MaTuyen
		{
			get
			{
				return this._LT_MaTuyen;
			}
			set
			{
				if ((this._LT_MaTuyen != value))
				{
					this.OnLT_MaTuyenChanging(value);
					this.SendPropertyChanging();
					this._LT_MaTuyen = value;
					this.SendPropertyChanged("LT_MaTuyen");
					this.OnLT_MaTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_HanhTrinhChay", DbType="NVarChar(512)")]
		public string LT_HanhTrinhChay
		{
			get
			{
				return this._LT_HanhTrinhChay;
			}
			set
			{
				if ((this._LT_HanhTrinhChay != value))
				{
					this.OnLT_HanhTrinhChayChanging(value);
					this.SendPropertyChanging();
					this._LT_HanhTrinhChay = value;
					this.SendPropertyChanged("LT_HanhTrinhChay");
					this.OnLT_HanhTrinhChayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_CuLy", DbType="Float")]
		public System.Nullable<double> LT_CuLy
		{
			get
			{
				return this._LT_CuLy;
			}
			set
			{
				if ((this._LT_CuLy != value))
				{
					this.OnLT_CuLyChanging(value);
					this.SendPropertyChanging();
					this._LT_CuLy = value;
					this.SendPropertyChanged("LT_CuLy");
					this.OnLT_CuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_LuuLuongQuyDinh", DbType="Int")]
		public System.Nullable<int> LT_LuuLuongQuyDinh
		{
			get
			{
				return this._LT_LuuLuongQuyDinh;
			}
			set
			{
				if ((this._LT_LuuLuongQuyDinh != value))
				{
					this.OnLT_LuuLuongQuyDinhChanging(value);
					this.SendPropertyChanging();
					this._LT_LuuLuongQuyDinh = value;
					this.SendPropertyChanged("LT_LuuLuongQuyDinh");
					this.OnLT_LuuLuongQuyDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TT_IdTrangThaiTuyen", DbType="Int")]
		public System.Nullable<int> TT_IdTrangThaiTuyen
		{
			get
			{
				return this._TT_IdTrangThaiTuyen;
			}
			set
			{
				if ((this._TT_IdTrangThaiTuyen != value))
				{
					this.OnTT_IdTrangThaiTuyenChanging(value);
					this.SendPropertyChanging();
					this._TT_IdTrangThaiTuyen = value;
					this.SendPropertyChanged("TT_IdTrangThaiTuyen");
					this.OnTT_IdTrangThaiTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_PL_IdLuongTuyen", DbType="Int")]
		public System.Nullable<int> LT_PL_IdLuongTuyen
		{
			get
			{
				return this._LT_PL_IdLuongTuyen;
			}
			set
			{
				if ((this._LT_PL_IdLuongTuyen != value))
				{
					this.OnLT_PL_IdLuongTuyenChanging(value);
					this.SendPropertyChanging();
					this._LT_PL_IdLuongTuyen = value;
					this.SendPropertyChanged("LT_PL_IdLuongTuyen");
					this.OnLT_PL_IdLuongTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LT_DC_IdLuongTuyen", DbType="BigInt")]
		public System.Nullable<long> LT_DC_IdLuongTuyen
		{
			get
			{
				return this._LT_DC_IdLuongTuyen;
			}
			set
			{
				if ((this._LT_DC_IdLuongTuyen != value))
				{
					this.OnLT_DC_IdLuongTuyenChanging(value);
					this.SendPropertyChanging();
					this._LT_DC_IdLuongTuyen = value;
					this.SendPropertyChanged("LT_DC_IdLuongTuyen");
					this.OnLT_DC_IdLuongTuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_CongTyVanTai")]
	public partial class QLVT_CongTyVanTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CT_IdCongTyVT;
		
		private string _TenCongTy;
		
		private System.Nullable<int> _MaCongTy;
		
		private System.Nullable<int> _SoLuongXe;
		
		private string _DiaChi;
		
		private System.Nullable<int> _TS_IdTinh_So;
		
		private EntitySet<QLVT_ThongTinXe> _QLVT_ThongTinXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCT_IdCongTyVTChanging(int value);
    partial void OnCT_IdCongTyVTChanged();
    partial void OnTenCongTyChanging(string value);
    partial void OnTenCongTyChanged();
    partial void OnMaCongTyChanging(System.Nullable<int> value);
    partial void OnMaCongTyChanged();
    partial void OnSoLuongXeChanging(System.Nullable<int> value);
    partial void OnSoLuongXeChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTS_IdTinh_SoChanging(System.Nullable<int> value);
    partial void OnTS_IdTinh_SoChanged();
    #endregion
		
		public QLVT_CongTyVanTai()
		{
			this._QLVT_ThongTinXes = new EntitySet<QLVT_ThongTinXe>(new Action<QLVT_ThongTinXe>(this.attach_QLVT_ThongTinXes), new Action<QLVT_ThongTinXe>(this.detach_QLVT_ThongTinXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_IdCongTyVT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CT_IdCongTyVT
		{
			get
			{
				return this._CT_IdCongTyVT;
			}
			set
			{
				if ((this._CT_IdCongTyVT != value))
				{
					this.OnCT_IdCongTyVTChanging(value);
					this.SendPropertyChanging();
					this._CT_IdCongTyVT = value;
					this.SendPropertyChanged("CT_IdCongTyVT");
					this.OnCT_IdCongTyVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTy", DbType="NVarChar(256)")]
		public string TenCongTy
		{
			get
			{
				return this._TenCongTy;
			}
			set
			{
				if ((this._TenCongTy != value))
				{
					this.OnTenCongTyChanging(value);
					this.SendPropertyChanging();
					this._TenCongTy = value;
					this.SendPropertyChanged("TenCongTy");
					this.OnTenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTy", DbType="Int")]
		public System.Nullable<int> MaCongTy
		{
			get
			{
				return this._MaCongTy;
			}
			set
			{
				if ((this._MaCongTy != value))
				{
					this.OnMaCongTyChanging(value);
					this.SendPropertyChanging();
					this._MaCongTy = value;
					this.SendPropertyChanged("MaCongTy");
					this.OnMaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongXe", DbType="Int")]
		public System.Nullable<int> SoLuongXe
		{
			get
			{
				return this._SoLuongXe;
			}
			set
			{
				if ((this._SoLuongXe != value))
				{
					this.OnSoLuongXeChanging(value);
					this.SendPropertyChanging();
					this._SoLuongXe = value;
					this.SendPropertyChanged("SoLuongXe");
					this.OnSoLuongXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdTinh_So", DbType="Int")]
		public System.Nullable<int> TS_IdTinh_So
		{
			get
			{
				return this._TS_IdTinh_So;
			}
			set
			{
				if ((this._TS_IdTinh_So != value))
				{
					this.OnTS_IdTinh_SoChanging(value);
					this.SendPropertyChanging();
					this._TS_IdTinh_So = value;
					this.SendPropertyChanged("TS_IdTinh_So");
					this.OnTS_IdTinh_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLVT_CongTyVanTai_QLVT_ThongTinXe", Storage="_QLVT_ThongTinXes", ThisKey="CT_IdCongTyVT", OtherKey="CT_IdCongTyVT")]
		public EntitySet<QLVT_ThongTinXe> QLVT_ThongTinXes
		{
			get
			{
				return this._QLVT_ThongTinXes;
			}
			set
			{
				this._QLVT_ThongTinXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QLVT_ThongTinXes(QLVT_ThongTinXe entity)
		{
			this.SendPropertyChanging();
			entity.QLVT_CongTyVanTai = this;
		}
		
		private void detach_QLVT_ThongTinXes(QLVT_ThongTinXe entity)
		{
			this.SendPropertyChanging();
			entity.QLVT_CongTyVanTai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLVT_ThongTinBenXe")]
	public partial class QLVT_ThongTinBenXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BX_IdBenXe;
		
		private string _TenBenXe;
		
		private System.Nullable<int> _MaBen;
		
		private System.Nullable<int> _TS_IdTinh_So;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _CoQuanQuanLy;
		
		private System.Nullable<double> _TongDienTich;
		
		private System.Nullable<double> _DienTich_XeKhach;
		
		private System.Nullable<double> _DienTich_PhuongTienKhac;
		
		private System.Nullable<double> _DienTich_NhaCho;
		
		private System.Nullable<int> _LoaiBenXe;
		
		private System.Nullable<int> _SoTuyenQuyHoach;
		
		private System.Nullable<int> _SoLuotXuatBenQuyHoach;
		
		private System.Nullable<int> _SoLuotXuatBenDangKy;
		
		private string _GhiChu;
		
		private System.Nullable<int> _TS_TT_IdTrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBX_IdBenXeChanging(int value);
    partial void OnBX_IdBenXeChanged();
    partial void OnTenBenXeChanging(string value);
    partial void OnTenBenXeChanged();
    partial void OnMaBenChanging(System.Nullable<int> value);
    partial void OnMaBenChanged();
    partial void OnTS_IdTinh_SoChanging(System.Nullable<int> value);
    partial void OnTS_IdTinh_SoChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCoQuanQuanLyChanging(string value);
    partial void OnCoQuanQuanLyChanged();
    partial void OnTongDienTichChanging(System.Nullable<double> value);
    partial void OnTongDienTichChanged();
    partial void OnDienTich_XeKhachChanging(System.Nullable<double> value);
    partial void OnDienTich_XeKhachChanged();
    partial void OnDienTich_PhuongTienKhacChanging(System.Nullable<double> value);
    partial void OnDienTich_PhuongTienKhacChanged();
    partial void OnDienTich_NhaChoChanging(System.Nullable<double> value);
    partial void OnDienTich_NhaChoChanged();
    partial void OnLoaiBenXeChanging(System.Nullable<int> value);
    partial void OnLoaiBenXeChanged();
    partial void OnSoTuyenQuyHoachChanging(System.Nullable<int> value);
    partial void OnSoTuyenQuyHoachChanged();
    partial void OnSoLuotXuatBenQuyHoachChanging(System.Nullable<int> value);
    partial void OnSoLuotXuatBenQuyHoachChanged();
    partial void OnSoLuotXuatBenDangKyChanging(System.Nullable<int> value);
    partial void OnSoLuotXuatBenDangKyChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTS_TT_IdTrangThaiChanging(System.Nullable<int> value);
    partial void OnTS_TT_IdTrangThaiChanged();
    #endregion
		
		public QLVT_ThongTinBenXe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BX_IdBenXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BX_IdBenXe
		{
			get
			{
				return this._BX_IdBenXe;
			}
			set
			{
				if ((this._BX_IdBenXe != value))
				{
					this.OnBX_IdBenXeChanging(value);
					this.SendPropertyChanging();
					this._BX_IdBenXe = value;
					this.SendPropertyChanged("BX_IdBenXe");
					this.OnBX_IdBenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenXe", DbType="NVarChar(512)")]
		public string TenBenXe
		{
			get
			{
				return this._TenBenXe;
			}
			set
			{
				if ((this._TenBenXe != value))
				{
					this.OnTenBenXeChanging(value);
					this.SendPropertyChanging();
					this._TenBenXe = value;
					this.SendPropertyChanged("TenBenXe");
					this.OnTenBenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBen", DbType="Int")]
		public System.Nullable<int> MaBen
		{
			get
			{
				return this._MaBen;
			}
			set
			{
				if ((this._MaBen != value))
				{
					this.OnMaBenChanging(value);
					this.SendPropertyChanging();
					this._MaBen = value;
					this.SendPropertyChanged("MaBen");
					this.OnMaBenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_IdTinh_So", DbType="Int")]
		public System.Nullable<int> TS_IdTinh_So
		{
			get
			{
				return this._TS_IdTinh_So;
			}
			set
			{
				if ((this._TS_IdTinh_So != value))
				{
					this.OnTS_IdTinh_SoChanging(value);
					this.SendPropertyChanging();
					this._TS_IdTinh_So = value;
					this.SendPropertyChanged("TS_IdTinh_So");
					this.OnTS_IdTinh_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(16)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuanQuanLy", DbType="NVarChar(MAX)")]
		public string CoQuanQuanLy
		{
			get
			{
				return this._CoQuanQuanLy;
			}
			set
			{
				if ((this._CoQuanQuanLy != value))
				{
					this.OnCoQuanQuanLyChanging(value);
					this.SendPropertyChanging();
					this._CoQuanQuanLy = value;
					this.SendPropertyChanged("CoQuanQuanLy");
					this.OnCoQuanQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDienTich", DbType="Float")]
		public System.Nullable<double> TongDienTich
		{
			get
			{
				return this._TongDienTich;
			}
			set
			{
				if ((this._TongDienTich != value))
				{
					this.OnTongDienTichChanging(value);
					this.SendPropertyChanging();
					this._TongDienTich = value;
					this.SendPropertyChanged("TongDienTich");
					this.OnTongDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_XeKhach", DbType="Float")]
		public System.Nullable<double> DienTich_XeKhach
		{
			get
			{
				return this._DienTich_XeKhach;
			}
			set
			{
				if ((this._DienTich_XeKhach != value))
				{
					this.OnDienTich_XeKhachChanging(value);
					this.SendPropertyChanging();
					this._DienTich_XeKhach = value;
					this.SendPropertyChanged("DienTich_XeKhach");
					this.OnDienTich_XeKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_PhuongTienKhac", DbType="Float")]
		public System.Nullable<double> DienTich_PhuongTienKhac
		{
			get
			{
				return this._DienTich_PhuongTienKhac;
			}
			set
			{
				if ((this._DienTich_PhuongTienKhac != value))
				{
					this.OnDienTich_PhuongTienKhacChanging(value);
					this.SendPropertyChanging();
					this._DienTich_PhuongTienKhac = value;
					this.SendPropertyChanged("DienTich_PhuongTienKhac");
					this.OnDienTich_PhuongTienKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_NhaCho", DbType="Float")]
		public System.Nullable<double> DienTich_NhaCho
		{
			get
			{
				return this._DienTich_NhaCho;
			}
			set
			{
				if ((this._DienTich_NhaCho != value))
				{
					this.OnDienTich_NhaChoChanging(value);
					this.SendPropertyChanging();
					this._DienTich_NhaCho = value;
					this.SendPropertyChanged("DienTich_NhaCho");
					this.OnDienTich_NhaChoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBenXe", DbType="Int")]
		public System.Nullable<int> LoaiBenXe
		{
			get
			{
				return this._LoaiBenXe;
			}
			set
			{
				if ((this._LoaiBenXe != value))
				{
					this.OnLoaiBenXeChanging(value);
					this.SendPropertyChanging();
					this._LoaiBenXe = value;
					this.SendPropertyChanged("LoaiBenXe");
					this.OnLoaiBenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTuyenQuyHoach", DbType="Int")]
		public System.Nullable<int> SoTuyenQuyHoach
		{
			get
			{
				return this._SoTuyenQuyHoach;
			}
			set
			{
				if ((this._SoTuyenQuyHoach != value))
				{
					this.OnSoTuyenQuyHoachChanging(value);
					this.SendPropertyChanging();
					this._SoTuyenQuyHoach = value;
					this.SendPropertyChanged("SoTuyenQuyHoach");
					this.OnSoTuyenQuyHoachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuotXuatBenQuyHoach", DbType="Int")]
		public System.Nullable<int> SoLuotXuatBenQuyHoach
		{
			get
			{
				return this._SoLuotXuatBenQuyHoach;
			}
			set
			{
				if ((this._SoLuotXuatBenQuyHoach != value))
				{
					this.OnSoLuotXuatBenQuyHoachChanging(value);
					this.SendPropertyChanging();
					this._SoLuotXuatBenQuyHoach = value;
					this.SendPropertyChanged("SoLuotXuatBenQuyHoach");
					this.OnSoLuotXuatBenQuyHoachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuotXuatBenDangKy", DbType="Int")]
		public System.Nullable<int> SoLuotXuatBenDangKy
		{
			get
			{
				return this._SoLuotXuatBenDangKy;
			}
			set
			{
				if ((this._SoLuotXuatBenDangKy != value))
				{
					this.OnSoLuotXuatBenDangKyChanging(value);
					this.SendPropertyChanging();
					this._SoLuotXuatBenDangKy = value;
					this.SendPropertyChanged("SoLuotXuatBenDangKy");
					this.OnSoLuotXuatBenDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS_TT_IdTrangThai", DbType="Int")]
		public System.Nullable<int> TS_TT_IdTrangThai
		{
			get
			{
				return this._TS_TT_IdTrangThai;
			}
			set
			{
				if ((this._TS_TT_IdTrangThai != value))
				{
					this.OnTS_TT_IdTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TS_TT_IdTrangThai = value;
					this.SendPropertyChanged("TS_TT_IdTrangThai");
					this.OnTS_TT_IdTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
